CREATE OR REPLACE VIEW npmrds_shapefile_:YEAR AS
  SELECT
    COALESCE(i.aadt, s.aadt) AS aadt,
    COALESCE(i.aadt_combi, s.aadt_combi) AS aadt_combi,
    COALESCE(i.aadt_singl, s.aadt_singl) AS aadt_singl,
    i.active_end_date,
    i.active_start_date,
    COALESCE(i.altrtename, s.altrtename) AS altrtename,
    COALESCE(i.border_set, s.border_set) AS border_set,
    s.conflation_year,
    COALESCE(i.country, s.country) AS country,
    COALESCE(i.county, s.county) AS county,
    COALESCE(i.direction, s.direction) AS direction,
    COALESCE(i.end_latitude, s.endlat) AS endlat,
    COALESCE(i.end_longitude, s.endlong) AS endlong,
    COALESCE(i.faciltype, s.faciltype) AS faciltype,
    s.firstname,
    COALESCE(i.frc, s.frc) AS frc,
    COALESCE(i.f_system, s.f_system) AS f_system,
    i.intersection,
    COALESCE(i.isprimary, s.isprimary) AS isprimary,
    COALESCE(i.miles, s.miles) AS miles,
    COALESCE(i.nhs, s.nhs) AS nhs,
    COALESCE(i.nhs_pct, s.nhs_pct) AS nhs_pct,
    s.npmrds_shapefile_version,
    i.download_timestamp,
    s.ogc_fid,
    i.road,
    s.roadname,
    s.roadnumber,
    i.road_order,
    COALESCE(i.route_numb, s.route_numb) AS route_numb,
    COALESCE(i.route_qual, s.route_qual) AS route_qual,
    COALESCE(i.route_sign, s.route_sign) AS route_sign,
    COALESCE(i.start_latitude, s.startlat) AS startlat,
    COALESCE(i.start_longitude, s.startlong) AS startlong,
    COALESCE(i.state, s.state) AS state,
    COALESCE(i.strhnt_pct, s.strhnt_pct) AS strhnt_pct,
    COALESCE(i.strhnt_typ, s.strhnt_typ) AS strhnt_typ,
    COALESCE(i.structype, s.structype) AS structype,
    COALESCE(i.thrulanes, s.thrulanes) AS thrulanes,
    i.timezone_name,
    COALESCE(i.tmc, s.tmc) AS tmc,
    COALESCE(i.tmclinear, s.tmclinear) AS tmclinear,
    s.tmctype,
    COALESCE(i.truck, s.truck) AS truck,
    i.type,
    COALESCE(i.urban_code, s.urban_code) AS urban_code,
    s.wkb_geometry,
    COALESCE(i.zip, s.zip) AS zip
  FROM npmrds_shapefile_:SHP_YEAR AS s
    INNER JOIN tmc_identification_:YEAR AS i
    USING (tmc)
;
