#!/bin/bash

set -e
set -a

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# source ../../../config/postgres.env.dev
source ../../config/postgres.env.pluto

ZIP_PATH='./base_data_bulk/vehicle_class/Continuous_Class_2015-2019.zip'
TABLE_NAME="highway_data_services_data.raw_continuous_vehicle_classification_bulk"

HEADER="$(
  unzip -p "$ZIP_PATH" |
  head -1 |
    tr '[:upper:]' '[:lower:]' |
    sed 's/"//g'
)"

COL_NUMS=$(tr ',' '\n' <<< "$HEADER" | nl)

COUNT_ID_COL_NUM=$( grep -i COUNT_ID <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
RCSTA_COL_NUM=$( grep -i RCSTA <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
YEAR_COL_NUM=$( grep -i YEAR <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
MONTH_COL_NUM=$( grep -i MONTH <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
DAY_COL_NUM=$( grep -i 'DAY$' <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
DATA_INTERVAL_COL_NUM=$( grep -i DATA_INTERVAL <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
FED_DIR_COL_NUM=$( grep -i FEDERAL_DIRECTION <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
LANE_CODE_COL_NUM=$( grep -i LANE_CODE <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )

AWK_CODE="!_[\$${RCSTA_COL_NUM},\$${YEAR_COL_NUM},\$${MONTH_COL_NUM},\$${DAY_COL_NUM},\$${DATA_INTERVAL_COL_NUM},\$${FED_DIR_COL_NUM},\$${LANE_CODE_COL_NUM}]++"

## Sort by station/time/dir/lane ascending, Count_ID desc
##   Count_ID contains the archive date so sorting in descending
##     order by that column assures the AWK filter keeps the latest version
##     for each station/time/dir/lane.
unzip -p "$ZIP_PATH" |
  tail -n+2 |
  sed 's/\r//; s/\s\{1,\}/ /g; s/"\s\{0,\}/"/g;  s/\s\{0,\}"/"/g; s/""//g; s/, /,/g; s/ ,/,/g' |
  sort \
    -t, \
    "-k$RCSTA_COL_NUM,$RCSTA_COL_NUM" \
    "-k$YEAR_COL_NUM,$YEAR_COL_NUM"n \
    "-k$MONTH_COL_NUM,$MONTH_COL_NUM"n \
    "-k$DAY_COL_NUM,$DAY_COL_NUM"n \
    "-k$DATA_INTERVAL_COL_NUM,$DATA_INTERVAL_COL_NUM"n \
    "-k$FED_DIR_COL_NUM,$FED_DIR_COL_NUM"n \
    "-k$LANE_CODE_COL_NUM,$LANE_CODE_COL_NUM"n \
    "-k$COUNT_ID_COL_NUM,$COUNT_ID_COL_NUM"r |
  awk -F',' "$AWK_CODE" |
  psql \
    -c 'BEGIN;' \
    -c "DELETE FROM $TABLE_NAME;" \
    -c "
      COPY $TABLE_NAME (
        $HEADER
      ) FROM STDIN WITH CSV;
    " \
    -c "CLUSTER $TABLE_NAME;" \
    -c 'COMMIT;'

popd >/dev/null
