#!/bin/bash

# $ head -1 CAD_020011_04012020.CSV | tr , '\n' | nl
#    1  Count_ID
#    2  Region
#    3  Region_Code
#    4  County_Code
#    5  Station
#    6  RCSTA
#    7  Functional_Class
#    8  Factor_Group
#    9  Latitude
#   10  Longitude
#   11  Specific_Recorder_Placement
#   12  Channel_Notes
#   13  Data_Type
#   14  Blank
#   15  Year
#   16  Month
#   17  Day
#   18  Day_of_week
#   19  Federal_Direction
#   20  Lane_Code
#   21  Total_Number_of_Lanes_in_direction
#   22  Data_Collection_Interval
#   23  Data_Interval
#   24  Class_F1
#   25  Class_F2
#   26  Class_F3
#   27  Class_F4
#   28  Class_F5
#   29  Class_F6
#   30  Class_F7
#   31  Class_F8
#   32  Class_F9
#   33  Class_F10
#   34  Class_F11
#   35  Class_F12
#   36  Class_F13
#   37  Unclassified
#   38  Total
#   39  Flag_Field


set -a

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# source ../../../config/postgres.env.dev
source ../../config/postgres.env.pluto

DATA_DIR='./base_data_weekly'
TABLE_NAME="highway_data_services_data.raw_continuous_vehicle_classification_weekly"
VIEW_NAME="highway_data_services.raw_continuous_vehicle_classification_view"

HEADER="$(
  find "$DATA_DIR" -type f -name '*.CSV' -exec head -1 {} \; |
    sed 's/\r//; s/"//g' |
    tr '[:upper:]' '[:lower:]' |
    sort -u
)"

# https://superuser.com/a/795465
if (( $( grep -c . <<< "$HEADER" ) > 1 )); then
  echo 'ERROR: Inconsistent file headers'
  exit 1
fi

COL_NUMS=$(tr ',' '\n' <<< "$HEADER" | nl)

COUNT_ID_COL_NUM=$( grep -i COUNT_ID <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
RCSTA_COL_NUM=$( grep -i RCSTA <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
YEAR_COL_NUM=$( grep -i YEAR <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
MONTH_COL_NUM=$( grep -i MONTH <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
DAY_COL_NUM=$( grep -i 'DAY$' <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
DATA_INTERVAL_COL_NUM=$( grep -i DATA_INTERVAL <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
FED_DIR_COL_NUM=$( grep -i FEDERAL_DIRECTION <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
LANE_CODE_COL_NUM=$( grep -i LANE_CODE <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )

AWK_CODE="!_[\$${RCSTA_COL_NUM},\$${YEAR_COL_NUM},\$${MONTH_COL_NUM},\$${DAY_COL_NUM},\$${DATA_INTERVAL_COL_NUM},\$${FED_DIR_COL_NUM},\$${LANE_CODE_COL_NUM}]++"

COL_NAMES="$(
  sed '
    s/total_number_of_lanes_in_direction/lanes_in_direction/
    s/data_collection_interval/collection_interval/
  ' <<< "$HEADER"
)"

# Output the data rows, removing the dupes
#   By naming the directories after the zip archives,
#     and sorting the files in reverse order,
#     we give preference to the latest ZIP archive.
find "$DATA_DIR" -type f -name '*.CSV' |
  sort --reverse |
  while read -r f; do
    # shellcheck disable=SC2086
    sed 's/\r//; s/\s\{1,\}/ /g; s/"\s\{0,\}/"/g;  s/\s\{0,\}"/"/g; s/""//g; s/, /,/g; s/ ,/,/g' "$f" |
      awk 'NR>1'
  done |
  sort \
    -t, --stable \
    "-k$RCSTA_COL_NUM,$RCSTA_COL_NUM" \
    "-k$YEAR_COL_NUM,$YEAR_COL_NUM"n \
    "-k$MONTH_COL_NUM,$MONTH_COL_NUM"n \
    "-k$DAY_COL_NUM,$DAY_COL_NUM"n \
    "-k$DATA_INTERVAL_COL_NUM,$DATA_INTERVAL_COL_NUM"n \
    "-k$FED_DIR_COL_NUM,$FED_DIR_COL_NUM"n \
    "-k$LANE_CODE_COL_NUM,$LANE_CODE_COL_NUM"n \
    "-k$COUNT_ID_COL_NUM,$COUNT_ID_COL_NUM"r |
  awk -F',' "$AWK_CODE" |
  psql \
    -c 'BEGIN;' \
    -c "DELETE FROM $TABLE_NAME;" \
    -c "
      COPY $TABLE_NAME (
        $COL_NAMES
      ) FROM STDIN WITH CSV;
    " \
    -c "CLUSTER $TABLE_NAME;" \
    -c "REFRESH MATERIALIZED VIEW $VIEW_NAME;" \
    -c "CLUSTER $VIEW_NAME;" \
    -c 'COMMIT;'

popd >/dev/null
