#!/usr/bin/env node

/* eslint no-console: 0, no-await-in-loop: 0 */

const assert = require('assert')

const _ = require('lodash');
const split2 = require('split2');
const { pipe, through } = require('mississippi');

let theMeasure
let accumulator;

pipe(
  process.stdin,
  split2(JSON.parse), // https://github.com/mcollina/split2#ndj---newline-delimited-json
  through.obj(
    function accumulateByTmc({ tmc, measure, attribute, value }, $, cb) {
      if (!theMeasure) {
        theMeasure = measure
      } else {
        assert(measure === theMeasure)
      }

      if (_.get(accumulator, 'tmc') !== tmc) {
        // If we have an initialized accumulator, emit it
        if (!_.isEmpty(accumulator)) {
          this.push(accumulator);
        }

        // initialize/reset accumulator
        accumulator = { tmc };
      }

      accumulator[attribute] = value;

      cb();
    },
    function flush(cb) {
      if (!_.isEmpty(accumulator)) {
        this.push(accumulator);
      }

      cb();
    }
  ),
  through.obj(function ndjsonTransformer(d, $, cb) {
    const { tmc } = d;
    const measureData = _.omit(d, 'tmc');

    const row = `"${tmc}","${theMeasure}","${JSON.stringify(measureData).replace(
      /"/g,
      '"""'
    )}"`;

    this.push(Buffer.from(`${row}\n`));
    cb();
  }),
  process.stdout,
  err => {
    if (err) {
      console.error(err);
      process.exit(1);
    }
  }
);
