CREATE TABLE inrix_shapefile (
  ogc_fid      INTEGER,
  tmc          CHARACTER VARYING PRIMARY KEY,
  tmctype      CHARACTER VARYING,
  roadnumber   CHARACTER VARYING,
  roadname     CHARACTER VARYING,
  firstname    CHARACTER VARYING,
  tmclinear    BIGINT,
  country      CHARACTER VARYING,
  state        CHARACTER VARYING,
  county       CHARACTER VARYING,
  zip          CHARACTER VARYING,
  direction    CHARACTER VARYING,
  startlat     DOUBLE PRECISION,
  startlong    DOUBLE PRECISION,
  endlat       DOUBLE PRECISION,
  endlong      DOUBLE PRECISION,
  miles        DOUBLE PRECISION,
  frc          BIGINT,
  border_set   CHARACTER VARYING,
  f_system     BIGINT,
  urban_code   BIGINT,
  faciltype    BIGINT,
  structype    BIGINT,
  thrulanes    BIGINT,
  route_numb   BIGINT,
  route_sign   BIGINT,
  route_qual   BIGINT,
  altrtename   CHARACTER VARYING,
  aadt         BIGINT,
  aadt_singl   BIGINT,
  aadt_combi   BIGINT,
  nhs          BIGINT,
  nhs_pct      BIGINT,
  strhnt_typ   BIGINT,
  strhnt_pct   BIGINT,
  truck        BIGINT,
  wkb_geometry GEOMETRY(MULTILINESTRING,4326)
) WITH (fillfactor=100);

