#!/bin/bash

set -e

read -r HEADER

COL_NUMS=$(tr ',' '\n' <<< "$HEADER" | nl)

RCSTA_COL_NUM=$( grep RCSTA <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
YEAR_COL_NUM=$( grep Year <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
MONTH_COL_NUM=$( grep Month <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
DAY_COL_NUM=$( grep Day <<< "$COL_NUMS"| grep -v Day_of_week | grep --only -e '[0-9]\{1,\}' )
DATA_INTERVAL_COL_NUM=$( grep Data_Interval <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
FED_DIR_COL_NUM=$( grep Federal_Direction <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )
LANE_CODE_COL_NUM=$( grep Lane_Code <<< "$COL_NUMS"| grep --only -e '[0-9]\{1,\}' )

echo "$HEADER"

sort \
  -t, \
  "-k$RCSTA_COL_NUM,$RCSTA_COL_NUM" \
  "-k$YEAR_COL_NUM,$YEAR_COL_NUM"n \
  "-k$MONTH_COL_NUM,$MONTH_COL_NUM"n \
  "-k$DAY_COL_NUM,$DAY_COL_NUM"n \
  "-k$DATA_INTERVAL_COL_NUM,$DATA_INTERVAL_COL_NUM"n \
  "-k$FED_DIR_COL_NUM,$FED_DIR_COL_NUM"n \
  "-k$LANE_CODE_COL_NUM,$LANE_CODE_COL_NUM"n
