-- SEE
--   * https://npmrds.ritis.org/analytics/help/#npmrds
--   * https://npmrds.ritis.org/static/help/docs/NPMRDS.pdf

CREATE TABLE public.tmc_metadata_:YEAR (
  tmc                      CHARACTER VARYING,
  roadnumber               CHARACTER VARYING,
  roadname                 CHARACTER VARYING,
  firstname                CHARACTER VARYING,
  tmclinear                INTEGER,
  country                  CHARACTER VARYING,
  state_name               CHARACTER VARYING,
  county_name              CHARACTER VARYING,
  zip                      CHARACTER VARYING,
  direction                CHARACTER VARYING,
  startlat                 DOUBLE PRECISION,
  startlong                DOUBLE PRECISION,
  endlat                   DOUBLE PRECISION,
  endlong                  DOUBLE PRECISION,
  miles                    DOUBLE PRECISION,
  frc                      SMALLINT,
  border_set               CHARACTER VARYING,
  f_system                 SMALLINT,
  faciltype                SMALLINT,
  structype                SMALLINT,
  thrulanes                SMALLINT,
  route_numb               INTEGER,
  route_sign               SMALLINT,
  route_qual               SMALLINT,
  altrtename               CHARACTER VARYING,
  aadt                     INTEGER,
  aadt_singl               INTEGER,
  aadt_combi               INTEGER,
  nhs                      SMALLINT,
  nhs_pct                  SMALLINT,
  strhnt_typ               SMALLINT,
  strhnt_pct               SMALLINT,
  truck                    SMALLINT,
  state                    CHARACTER(2),
  is_interstate            BOOLEAN,
  is_controlled_access     BOOLEAN,
  avg_speedlimit           REAL,
  mpo_code                 CHARACTER VARYING,
  mpo_acrony               CHARACTER VARYING,
  mpo_name                 CHARACTER VARYING,
  ua_code                  CHARACTER VARYING,
  ua_name                  CHARACTER VARYING,
  congestion_level         TRAFFIC_DIST_CONGESTION_LEVEL_TYPE,
  directionality           TRAFFIC_DIST_DIRECTIONALITY_TYPE,
  bounding_box             BOX2D,
  avg_vehicle_occupancy    REAL,
  state_code               CHARACTER(2),
  county_code              CHARACTER(5),

  -- From tmc_identification
  type                     CHARACTER VARYING,
  road_order               REAL,
  isprimary                SMALLINT,
  timezone_name            CHARACTER VARYING,
  active_start_date        DATE,
  active_end_date          DATE
);
