CREATE TABLE public.tmc_metadata_:YEAR (
  tmc                      CHARACTER VARYING,
  tmctype                  CHARACTER VARYING,
  roadnumber               CHARACTER VARYING,
  roadname                 CHARACTER VARYING,
  firstname                CHARACTER VARYING,
  tmclinear                BIGINT,
  country                  CHARACTER VARYING,
  state_name               CHARACTER VARYING,
  county_name              CHARACTER VARYING,
  zip                      CHARACTER VARYING,
  direction                CHARACTER VARYING,
  startlat                 DOUBLE PRECISION,
  startlong                DOUBLE PRECISION,
  endlat                   DOUBLE PRECISION,
  endlong                  DOUBLE PRECISION,
  miles                    DOUBLE PRECISION,
  frc                      BIGINT,
  border_set               CHARACTER VARYING,
  f_system                 BIGINT,
  urban_code               BIGINT,
  faciltype                BIGINT,
  structype                BIGINT,
  thrulanes                BIGINT,
  route_numb               BIGINT,
  route_sign               BIGINT,
  route_qual               BIGINT,
  altrtename               CHARACTER VARYING,
  aadt                     BIGINT,
  aadt_singl               BIGINT,
  aadt_combi               BIGINT,
  nhs                      BIGINT,
  nhs_pct                  BIGINT,
  strhnt_typ               BIGINT,
  strhnt_pct               BIGINT,
  truck                    BIGINT,
  state                    CHARACTER(2),
  is_interstate            BOOLEAN,
  is_controlled_access     BOOLEAN,
  avg_speedlimit           REAL,
  mpo_code                 CHARACTER VARYING,
  mpo_acrony               CHARACTER VARYING,
  mpo_name                 CHARACTER VARYING,
  ua_code                  CHARACTER VARYING,
  ua_name                  CHARACTER VARYING,
  congestion_level         TRAFFIC_DIST_CONGESTION_LEVEL_TYPE,
  directionality           TRAFFIC_DIST_DIRECTIONALITY_TYPE,
  bounding_box             BOX2D,
  avg_vehicle_occupancy    REAL,
  state_code               CHARACTER(2),
  county_code              CHARACTER(5),
  conflation_year          SMALLINT,
  npmrds_shapefile_version CHARACTER VARYING,

  CONSTRAINT tmc_metadata_year_check CHECK (conflation_year = :YEAR)
);
