#!/usr/bin/env node

/* eslint no-unused-expressions: 0, camelcase: 0 */

const { spawn } = require('child_process');

const yargs = require('yargs');

const singleYearInvariantMessage =
  'The requested startDate and endDate MUST be within a single calendar year.';

const verifySingleYear = (startDate, endDate) => {
  if (startDate.slice(0, 4) !== endDate.slice(0, 4)) {
    console.error(`ERROR: ${singleYearInvariantMessage}`);
    process.exit(1);
  }
};

yargs
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .option({
    pg_env: {
      type: 'string',
      demand: false,
      choices: ['production', 'development'],
      default: 'development'
    }
  })
  .command({
    command: 'load_state_year_tmc_metadata',
    desc: 'Create the tmc_metadata table for the specified state and year',
    builder: {
      year: { type: 'number', demand: true },
      state: { type: 'string', demand: true }
    },
    handler: ({ year, state, pg_env }) => {
      spawn('make', ['db/load-state-year-tmc-metadata'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { YEAR: year, STATE: state, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'refresh_state_tmc_date_ranges_table',
    desc:
      'Refresh the tmc data date ranges table for the specified state (creating the table if necessary).',
    builder: {
      state: { type: 'string', demand: true }
    },
    handler: ({ state, pg_env }) => {
      spawn('make', ['db/refresh-state-tmc-date-ranges-table'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { STATE: state, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'download_and_partition_npmrds_shapefile',
    desc:
      "Download the specified country's shapefile for the specified conflation year",
    builder: {
      year: { type: 'number', demand: true },
      country: { type: 'string', demand: true }
    },
    handler: ({ year, country, pg_env }) => {
      spawn('make', ['etl/download-and-partition-npmrds-shapefile'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { YEAR: year, COUNTRY: country, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'upload_state_npmrds_shapefile_from_country_tar',
    desc:
      "Load the specified state's shapefile from the specified tar archive. (NOTE: For Canada, state=cn. Provinces created automatically.)",
    builder: {
      tarArchivePath: { type: 'string', demand: true },
      state: { type: 'string', demand: true }
    },
    handler: ({ tarArchivePath, state, pg_env }) => {
      spawn('make', ['db/upload-state-npmrds-shapefile-from-country-tar'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { TAR_ARCHIVE_PATH: tarArchivePath, STATE: state, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'upload_zipped_state_npmrds_shapefile',
    desc: 'Load the specified shapefile zip archive.',
    builder: {
      shpZipPath: { type: 'string', demand: true },
      year: { type: 'number', demand: true },
      state: { type: 'string', demand: true }
    },
    handler: ({ shpZipPath, year, state, pg_env }) => {
      spawn('make', ['db/upload-zipped-npmrds-shapefile'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: {
          STATE: state,
          SHP_ZIP_PATH: shpZipPath,
          YEAR: year,
          PG_ENV: pg_env
        }
      });
    }
  })
  .command({
    command: 'create_state_placeholder_npmrds_shapefile',
    desc:
      "Create a placeholder npmrds_shapefile table for the placeholderYear using the sourceYear's npmrds_shapefile table.",
    builder: {
      placeholderYear: { type: 'number', demand: true },
      sourceYear: { type: 'number', demand: true },
      state: { type: 'string', demand: true }
    },
    handler: ({ placeholderYear, sourceYear, state, pg_env }) => {
      spawn('make', ['db/create-state-placeholder-npmrds-shapefile'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: {
          STATE: state,
          PLACEHOLDER_YEAR: placeholderYear,
          SOURCE_YEAR: sourceYear,
          PG_ENV: pg_env
        }
      });
    }
  })
  .command({
    command: 'upload-state-year-tmc-identification-from-etl-tar',
    desc: `The ZIP archives from RITIS' Massive Data Downloader include a file named TMC_Identification.
      NOTE: This command creates all required tables and loads the TMC_Identification from the
        specified tarArchivePath. If the specified archive is newer than the current default
        database TMC_Identification file, it will  become the default.`,
    builder: {
      tarArchivePath: { type: 'string', demand: true }
    },
    handler: ({ tarArchivePath, pg_env }) => {
      spawn('make', ['db/upload-state-year-tmc-identification-from-etl-tar'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { TAR_ARCHIVE_PATH: tarArchivePath, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'create_npmrds_state_yrmo_table',
    desc: 'Create state npmrds table for the year and month',
    builder: {
      year: { type: 'number', demand: true },
      month: { type: 'number', demand: true }
    },
    handler: ({ year, month, pg_env }) => {
      spawn('make', ['db/create-npmrds-state-yrmo-table'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { YEAR: year, MONTH: month, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'create_geography_metadata',
    desc: 'Create (or replace) the geography_metadata VIEW.',
    handler: ({ pg_env }) => {
      spawn('make', ['db/create-geography-metadata-view'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'download_urban_area_boundaries_shapefile',
    desc:
      'Download the TIGER Urban Area Shapefile from census.gov for the specified year',
    builder: {
      year: { type: 'number', demand: true }
    },
    handler: ({ year }) => {
      spawn('make', ['scraping/download-urban-area-boundaries-shapefile'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { YEAR: year }
      });
    }
  })
  .command({
    command: 'download_npmrds_data',
    desc:
      'Download and transform the NPMRDS Data from the RITIS Massive Data Downloader',
    builder: {
      downloadLinks: {
        type: 'string',
        desc: 'The download links as a comma-separated list.',
        demand: true
      }
    },
    handler: ({ downloadLinks }) => {
      spawn('make', ['etl/download-and-transform-npmrds-data'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { DOWNLOAD_LINKS: downloadLinks }
      });
    }
  })
  // TODO: Make dataFilePath an absolute path before passing to make.
  .command({
    command: 'upload_npmrds_state_yrmo',
    desc: "Load the specified state's month of NPMRDS data into the database",
    builder: {
      state: { type: 'string', demand: true },
      year: { type: 'number', demand: true },
      month: { type: 'number', demand: true },
      dataFilePath: { type: 'string', demand: true }
    },
    handler: ({ pg_env, state, year, month, dataFilePath }) => {
      spawn('make', ['db/upload-npmrds-state-yrmo'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: {
          PG_ENV: pg_env,
          STATE: state,
          YEAR: year,
          MONTH: month,
          DATA_FILE_PATH: dataFilePath
        }
      });
    }
  })
  .command({
    command: 'create_pm3_tables',
    desc: 'Create the PM3 tables.',
    handler: ({ pg_env }) => {
      spawn('make', ['db/create_pm3_tables'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: `${pg_env}` }
      });
    }
  })
  .command({
    command: 'create_pm3_authoritative_geolevel_mview',
    desc: 'Create the PM3 Geography Level Materialized View.',
    handler: ({ pg_env }) => {
      spawn('make', ['db/create_pm3_authoritative_geolevel_mview'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: `${pg_env}` }
      });
    }
  })
  .command({
    command: 'cluster_pm3_eav_append_only_table',
    desc: 'Cluster the pm3_eav_append_only_table on the tmc column.',
    handler: ({ pg_env }) => {
      spawn('make', ['db/cluster_pm3_eav_append_only_table'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: `${pg_env}` }
      });
    }
  })
  .command({
    command: 'load_avgtt_table_for_state_year',
    desc:
      'Load the avgtt for the specified state and year of data. (Creates the table if necessary.)',
    builder: {
      state: { type: 'string', demand: true },
      year: { type: 'number', demand: true }
    },
    handler: ({ state, year, pg_env }) => {
      spawn('make', ['db/load-state-year-avgtt-table'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: pg_env, STATE: state, YEAR: year }
      });
    }
  })
  .command({
    command: 'create_pm3_authoritative_view',
    desc:
      'Create the pm3_authoritative_view materialized view. (Updates the view if it exists.)',
    handler: ({ pg_env }) => {
      spawn('make', ['db/create_pm3_authoritative_view'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: pg_env }
      });
    }
  })
  // db/create-routing-tables-and-funcitons-for-year
  .command({
    command: 'create-routing-tables-and-funcitons-for-year',
    desc:
      'Create the tables and functions used for creating routes. (Drops & re-creates the tables if they exist.)',
    builder: {
      year: { type: 'number', demand: true }
    },
    handler: ({ year, pg_env }) => {
      spawn('make', ['db/create-routing-tables-and-funcitons-for-year'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { PG_ENV: pg_env, YEAR: year }
      });
    }
  })
  .command({
    command: 'transcom_events_etl',
    desc: `Transcom Events ETL Pipeline

      * Creates a tar archive with raw events download from the TransCom API as a gzipped NDJSON file, and a gzipped CSV with the downloaded events transformed for loading into the database.

      * Loads the downloaded events into the specified (via pg_env flag) database.
      
      NOTE: The requested startDate and endDate MUST be within a single calendar year.

      NOTE: Does not CLUSTER transcom.transcom_events. Must be manually done after loading.
    `,
    builder: {
      startDate: {
        type: 'string',
        demand: true,
        describe: 'Data start date. (Format YYYYMMDD)'
      },
      endDate: {
        type: 'string',
        demand: true,
        describe: 'Data end date, inclusive. (Format YYYYMMDD)'
      }
    },
    handler: ({ startDate, endDate, pg_env }) => {
      verifySingleYear(startDate, endDate);
      spawn('make', ['etl/transcom_events'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { START_DATE: startDate, END_DATE: endDate, PG_ENV: pg_env }
      });
    }
  })
  .command({
    command: 'create-mabox-tileset-for-year',
    desc: "Create mbtiles file from the year's shapfile.",
    builder: {
      year: {
        type: 'string',
        demand: true,
        describe: 'Data start date. (Format YYYYMMDD)'
      }
    },
    handler: ({ year, pg_env }) => {
      spawn('make', ['mapbox/create-tileset-for-year'], {
        cwd: __dirname,
        stdio: 'inherit',
        env: { YEAR: year, PG_ENV: pg_env }
      });
    }
  })
  .demandCommand()
  .recommendCommands()
  .strict()
  .wrap(yargs.terminalWidth() / 1.618).argv;
