#!/usr/bin/env node

const fs = require('fs')
const _ = require('lodash')

const stateAbbreviations = require('./stateAbbreviations')

const contents = fs.readFileSync(0, 'utf-8').toString().replace(/ /g, '')

const stateNames = Object.keys(stateAbbreviations)

let foundOne = false

for (let i = 0; i < stateNames.length; ++i) {
  const stateName = stateNames[i]
  const re = new RegExp(stateName, 'i')

  const state = contents.match(re)

  if (state) {
    process.stdout.write(`${foundOne ? '\n' : ''}${_.startCase(state)}`)
    foundOne = true
  }
}

if (!foundOne) {
  console.error('ERROR: Could not find state name.')
  process.exit(1)
}
