#!/usr/bin/env node

const _ = require('lodash')

const stateAbbrs = {
  'alabama': 'al',
  'alaska': 'ak',
  'arizona': 'az',
  'arkansas': 'ar',
  'california': 'ca',
  'colorado': 'co',
  'connecticut': 'ct',
  'delaware': 'de',
  'florida': 'fl',
  'georgia': 'ga',
  'hawaii': 'hi',
  'idaho': 'id',
  'illinois': 'il',
  'indiana': 'in',
  'iowa': 'ia',
  'kansas': 'ks',
  'kentucky': 'ky',
  'louisiana': 'la',
  'maine': 'me',
  'maryland': 'md',
  'massachusetts': 'ma',
  'michigan': 'mi',
  'minnesota': 'mn',
  'mississippi': 'ms',
  'missouri': 'mo',
  'montana': 'mt',
  'nebraska': 'ne',
  'nevada': 'nv',
  'newhampshire': 'nh',
  'newjersey': 'nj',
  'newmexico': 'nm',
  'newyork': 'ny',
  'northcarolina': 'nc',
  'northdakota': 'nd',
  'ohio': 'oh',
  'oklahoma': 'ok',
  'oregon': 'or',
  'pennsylvania': 'pa',
  'rhodeisland': 'ri',
  'southcarolina': 'sc',
  'southdakota': 'sd',
  'tennessee': 'tn',
  'texas': 'tx',
  'utah': 'ut',
  'vermont': 'vt',
  'virginia': 'va',
  'washington': 'wa',
  'westvirginia': 'wv',
  'wisconsin': 'wi',
  'wyoming': 'wy',

  'districtofcolumbia': 'dc',
  'district': 'dc',
  'guam': 'gu',
  'puertorico': 'pr',
  'virginislands': 'vi',

  'canada': 'cn',
  'mexico': 'mx',

  'alberta': 'ab',
  'britishcolumbia': 'bc',
  'manitoba': 'mb',
  'newbrunswick': 'nb',
  'newfoundlandandlabrador': 'nl',
  'northwestterritories': 'nt',
  'novascotia': 'ns',
  'nunavut': 'nu',
  'ontario': 'on',
  'princeedwardisland': 'pe',
  'quebec': 'qc',
  'québec': 'qc',
  'saskatchewan': 'sk',
  'yukon': 'yt',
}

if (require.main === module) {
  const stateName = process.argv[2]

  if (typeof stateName !== 'string') {
    console.error('USAGE: pass the state name as the only CLI parameter, quoting if necessary')
    process.exit(1)
  }

  const cleanedStateName = stateName.toLowerCase().replace(/\?\?/g, '.').replace(/ /g, '')

  const regex = new RegExp(`^${cleanedStateName}$`, 'i')

  const stateAbbr = _.find(stateAbbrs, (_v, k) => k.match(regex))

  if (!stateAbbr) {
    console.error('ERROR: Unrecognized state name')
    process.exit(1)
  }

  process.stdout.write(stateAbbr)
}

module.exports = stateAbbrs

