#!/bin/bash

set -e
set -a

# Change CWD to this script's directory.
pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

if [ "$PG_ENV" = "production" ]; then
  . ../../../config/postgres.env.prod
else
	. ../../../config/postgres.env.dev
fi

export PGOPTIONS='--client-min-messages=warning';

psql --quiet -f ../../../sql/pm3_calculator_metadata/create_pm3_calculator_metadata_table.sql
psql --quiet -f ../../../sql/pm3_calculator_output/create_root_table.sql
psql --quiet -f ../../../sql/pm3_calculation_versions/create_pm3_calculation_versions_db_objects.sql
psql --quiet -f ../../../sql/pm3_calculator_data_provenances/create_pm3_calculator_data_provenances_views.sql
psql --quiet -f ../../../sql/pm3_calculator_output_versions_view/create_pm3_calculator_output_versions_view.sql
psql --quiet -f ../../../sql/pm3_geolevel_calculation_versions/create_pm3_versioned_geolevel_measures_table.sql
psql --quiet -f ../../../sql/pm3_geolevel_calculation_versions/create_calculate_pm3_geolevel_calculation_version_fn.sql

popd >/dev/null
