#!/usr/bin/env node

/* eslint no-console: 0, no-await-in-loop: 0 */

const { execSync } = require('child_process');
const { isAbsolute, join } = require('path');
const { existsSync, readdirSync, readFileSync } = require('fs');

const { Client } = require('pg');

const yargs = require('yargs');
const envFile = require('node-env-file');

const cliArgsSpec = {
  calculatorOutputDir: {
    type: 'string',
    demand: true
  },
  pg_env: {
    type: 'string',
    demand: false,
    choices: ['production', 'development'],
    default: 'development'
  }
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { pg_env, calculatorOutputDir } = argv;

const configPath = join(
  __dirname,
  pg_env === 'production'
    ? '../../../config/postgres.env.prod'
    : '../../../config/postgres.env.dev'
);
envFile(configPath);

process.env.PGOPTIONS = '--client-min-messages=warning';

if (!calculatorOutputDir) {
  console.error(
    'ERROR: The calculator output directory path must be specified as the 1st cli argument.'
  );
  process.exit(1);
}

const sortedCalculatorOutputAccumulatorPath = join(
  __dirname,
  './utils/sortedCalculatorOutputAccumulator'
);

const calculatorOutputDirPath = isAbsolute(calculatorOutputDir)
  ? calculatorOutputDir
  : join(process.cwd(), calculatorOutputDir);

const measureOutputFiles = readdirSync(calculatorOutputDirPath).filter(f =>
  /\.ndjson$/.test(f)
);

if (!existsSync(calculatorOutputDirPath)) {
  console.error(
    `ERROR: The specified calculator output directory ${calculatorOutputDirPath} does not exist.`
  );
  process.exit(1);
}

// Create the PM3 Tables
execSync(
  `psql -f ${join(
    __dirname,
    '../../../sql/pm3_calculator_metadata/create_pm3_calculator_metadata_table.sql'
  )}`
);
execSync(
  `psql -f ${join(
    __dirname,
    '../../../sql/pm3_calculator_output/create_root_table.sql'
  )}`
);

const createPm3CalculatorOutputTablePartition = pm3calc_id => {
  execSync(
    `psql -v PM3CALC_ID=${pm3calc_id} -f ${join(
      __dirname,
      '../../../sql/pm3_calculator_output/create_partition_table.sql'
    )}`
  );
};

const finishPm3CalculatorOutputTablePartition = pm3calc_id => {
  execSync(
    `psql -v PM3CALC_ID=${pm3calc_id} -f ${join(
      __dirname,
      '../../../sql/pm3_calculator_output/finish_partition_table.sql'
    )}`
  );
};

const calculatorMetadataFilePath = join(
  calculatorOutputDirPath,
  'calculator_metadata.json'
);

if (!existsSync(calculatorMetadataFilePath)) {
  console.error(
    `ERROR: ${calculatorOutputDirPath} does not contain a calculator_metadata.json file.`
  );
  process.exit(1);
}

const calculatorMetadata = JSON.parse(
  readFileSync(calculatorMetadataFilePath, {
    encoding: 'utf8'
  })
);

if (calculatorMetadata.calculatorSettings.outputFileFormat !== 'NDJSON') {
  console.error(
    'ERROR: The loader requires the calculator was run with --outputFileFormat=NDJSON'
  );
  process.exit(1);
}

if (calculatorMetadata.calculatorSettings.outputFormat !== 'EAV') {
  console.error(
    'ERROR: The loader requires the calculator was run with --outputFormat=EAV'
  );
  process.exit(1);
}

const insertPM3CalculatorMetadata = async client => {
  const {
    rows: [{ id }]
  } = await client.query(
    'INSERT INTO pm3.pm3_calculator_metadata (metadata) VALUES ($1) RETURNING id',
    [calculatorMetadata]
  );

  return id;
};

// NOTE: Will cascade and clean up pm3_calculator_output as well.
const deletePM3CalculatorMetadata = (client, pm3calc_id) =>
  client.query('DELETE FROM pm3.pm3_calculator_metadata WHERE id = $1', [
    pm3calc_id
  ]);

const loadOutputFile = (pm3calc_id, outputFilePath) => {
  if (existsSync(outputFilePath)) {
    createPm3CalculatorOutputTablePartition(pm3calc_id);

    execSync(`
      jq -s -c 'sort_by(.tmc, .attribute)[]' ${outputFilePath} |
        ${sortedCalculatorOutputAccumulatorPath} |
        psql -c '
          COPY pm3_calculator_output_partitions.pm3_calculator_output_${pm3calc_id} (
            tmc,
            measure,
            measure_data
          ) FROM STDIN WITH CSV  
    '`);
  }
};

const loadCalculatorOutput = pm3calc_id => {
  for (let i = 0; i < measureOutputFiles.length; ++i) {
    const outputFileName = measureOutputFiles[i];
    const outputFilePath = join(calculatorOutputDir, outputFileName);

    loadOutputFile(pm3calc_id, outputFilePath);
  }

  finishPm3CalculatorOutputTablePartition(pm3calc_id);
};

(async () => {
  let pm3calc_id;

  try {
    const client = new Client();
    await client.connect();

    try {
      pm3calc_id = await insertPM3CalculatorMetadata(client);

      loadCalculatorOutput(pm3calc_id);
    } catch (err) {
      // Clean up failed load. DELETE cascades.
      console.error('DELETING all data from this pm3_calculator run.');
      await deletePM3CalculatorMetadata(client, pm3calc_id);
      console.error(err.message);
    } finally {
      client.end();
    }
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
