#!/bin/bash

set -e
set -a

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

source ./config/postgres.env.prod
source ./config/env

psql -c "
  COPY (
    SELECT
        a.*
      FROM _transcom_admin.transcom_events_expanded AS a
        INNER JOIN public.tl_2017_us_county AS b
          ON (
            ST_Intersects(
              b.geom,
              public.ST_Transform(
                public.ST_SetSRID(
                  public.ST_MakePoint(
                    a.point_long,
                    a.point_lat
                  ),
                  4269 -- NAD83 -- EPSG:4269
                ),
                4326  -- EPSG:4326
              )
            )
          )
        WHERE (
          ( b.geoid = '$COUNTY_CODE' )
          AND
          (
            (EXTRACT(YEAR FROM start_date_time) = $YEAR)
            AND
            (EXTRACT(YEAR FROM close_date) = $YEAR)
          )
        )
  ) TO STDOUT WITH CSV HEADER
" > data/transcom_events_expanded.$COUNTY_CODE.$YEAR.csv

popd >/dev/null
