#!/bin/bash

set -e
set -a

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

source ./config/postgres.env.prod
source ./config/env

pg_dump \
    --dbname=npmrds_production \
    --no-owner \
    --no-privileges \
    --table='transcom.transcom_events_2' \
> transcom_events_2.sql

popd >/dev/null
