#!/bin/bash

set -e
set -a

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

source ./config/postgres.env.prod
source ./config/env

OUTPUT_GPKG="./data/transcom_events_$YEAR.gpkg"

ogr2ogr \
  -f 'GPKG' \
  -skipfailures \
  -s_srs EPSG:4326 \
  -t_srs EPSG:4326 \
  $OUTPUT_GPKG \
  PG:"host=$PGHOST user=$PGUSER dbname=$PGDATABASE password=$PGPASSWORD" \
  -nln transcom_events_expanded \
  -sql "
    SELECT
        *
      FROM _transcom_admin.transcom_events_expanded AS a
        INNER JOIN public.tl_2017_us_county AS b
          ON (
            ST_Intersects(
              b.geom,
              public.ST_Transform(
                public.ST_SetSRID(
                  public.ST_MakePoint(
                    a.point_long,
                    a.point_lat
                  ),
                  4269 -- NAD83 -- EPSG:4269
                ),
                4326  -- EPSG:4326
              )
            )
          )
        WHERE (
          ( b.geoid = '$COUNTY_CODE' )
          AND
          (
            (EXTRACT(YEAR FROM start_date_time) = $YEAR)
            AND
            (EXTRACT(YEAR FROM close_date) = $YEAR)
          )
        )
        ORDER BY RANDOM()
        LIMIT 1000
  "

popd >/dev/null
