#!/bin/bash

set -e
set -a

# shellcheck disable=SC2153
if [[ -z "$STATE" ]]; then
  (>&2 echo "ERROR: You must specify the STATE as an ENV variable.")
  exit 1
fi

if [[ -z "$SOURCE_YEAR" ]]; then
  (>&2 echo "ERROR: You must specify the SOURCE_YEAR as an ENV variable.")
  exit 1
fi

if [[ -z "$PLACEHOLDER_YEAR" ]]; then
  (>&2 echo "ERROR: You must specify the PLACEHOLDER_YEAR as an ENV variable.")
  exit 1
fi

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# Load the STATE_ABBREVIATIONS hash table
. ../../../bin/stateAbbreviations.sh

# source the database connection config.
if [ "$PG_ENV" = "production" ]; then
	. ../../../config/postgres.env.prod
else
	. ../../../config/postgres.env.dev
fi

# Last chance to kill script... just in case
(>&2 echo "PostgreSQL Server: ${PGHOST}:${PGPORT}")
sleep 3

export PGOPTIONS='--client-min-messages=warning' 

psql \
  --quiet \
  -v STATE="$STATE" -v YEAR="$PLACEHOLDER_YEAR" \
  -c 'BEGIN;' \
  -f ../../../sql/npmrds_shapefile/root/createRootYearNPMRDSShapefileTable.sql \
  -c 'COMMIT;'

psql \
  -v STATE="${STATE}" \
  -v PLACEHOLDER_YEAR="${PLACEHOLDER_YEAR}" \
  -v SOURCE_YEAR="${SOURCE_YEAR}" \
  -f '../../../sql/placeholder_npmrds_shapefile/createPlaceholderStateNPMRDSShapefileYearTable.sql';

# The following applies only when loading Canada's shapefile.
STATES_IN_PLACEHOLDER_TABLE="$(psql -t -c "
  SELECT DISTINCT state
    FROM \"${STATE}\".npmrds_shapefile_${PLACEHOLDER_YEAR}
    ORDER BY state;
" | sed '/^$/d; s/^\s*//g')"

while read -r state_name; do
  state="${STATE_ABBREVIATIONS[${state_name,,}]}";

  # If we have a 2 char code for the state
  #   and the state is not the same as the STATE name
  if [[ ! -z "$state" && "$STATE" != "$state" ]]; then
    VIEW_FULL_NAME="\"${state}\".npmrds_shapefile_${PLACEHOLDER_YEAR}"

    # If the state specific view does not exist
    if ! psql -c "\d $VIEW_FULL_NAME" > /dev/null 2>&1; then
      CREATE_VIEW_SQL="
        CREATE OR REPLACE VIEW $VIEW_FULL_NAME
          AS
            SELECT
                *
              FROM \"${STATE}\".npmrds_shapefile_${SOURCE_YEAR}
              WHERE state = '${state_name}'
        ; "

      VIEW_COMMENT="Placeholder view created by cloning \"${STATE}\".npmrds_shapefile_${SOURCE_YEAR}"

      psql \
        --quiet \
        -c 'BEGIN;' \
        -c "CREATE SCHEMA IF NOT EXISTS \"${state}\";" \
        -c "$CREATE_VIEW_SQL" \
        -c "COMMENT ON VIEW $VIEW_FULL_NAME IS '${VIEW_COMMENT}'" \
        -c 'COMMIT;'
    fi
  fi
done <<< "$STATES_IN_PLACEHOLDER_TABLE"

popd >/dev/null
