CREATE TABLE public.npmrds_shapefile_:YEAR (
  ogc_fid                  INTEGER,
  tmc                      CHARACTER VARYING,
  tmctype                  CHARACTER VARYING,
  roadnumber               CHARACTER VARYING,
  roadname                 CHARACTER VARYING,
  firstname                CHARACTER VARYING,
  tmclinear                INTEGER,
  country                  CHARACTER VARYING,
  state                    CHARACTER VARYING,
  county                   CHARACTER VARYING,
  zip                      CHARACTER VARYING,
  direction                CHARACTER VARYING,
  startlat                 DOUBLE PRECISION,
  startlong                DOUBLE PRECISION,
  endlat                   DOUBLE PRECISION,
  endlong                  DOUBLE PRECISION,
  miles                    DOUBLE PRECISION,
  frc                      SMALLINT,
  border_set               CHARACTER VARYING,
  isprimary                SMALLINT, 
  f_system                 SMALLINT,
  urban_code               INTEGER,
  faciltype                SMALLINT,
  structype                SMALLINT,
  thrulanes                SMALLINT,
  route_numb               INTEGER,
  route_sign               SMALLINT,
  route_qual               SMALLINT,
  altrtename               CHARACTER VARYING,
  aadt                     INTEGER,
  aadt_singl               INTEGER,
  aadt_combi               INTEGER,
  nhs                      SMALLINT,
  nhs_pct                  SMALLINT,
  strhnt_typ               SMALLINT,
  strhnt_pct               SMALLINT,
  truck                    SMALLINT,
  wkb_geometry             GEOMETRY(MULTILINESTRING,4326),
  conflation_year          SMALLINT DEFAULT :YEAR,
  npmrds_shapefile_version CHARACTER VARYING,

  CONSTRAINT tmc_metadata_year_check CHECK (conflation_year = :YEAR)
) WITH (fillfactor=100);

