#!/usr/bin/env node

// https://wiki.openstreetmap.org/wiki/Way#Examples
//   The nodes defining the geometry of the way are enumerated in the correct order,
//     and indicated only by reference using their unique identifier.
//   These nodes must have been already defined separately with their coordinates.
//
// https://wiki.openstreetmap.org/wiki/Relation:restriction

const { execSync } = require('child_process');
const { createReadStream } = require('fs');

const yargs = require('yargs');
const XmlStream = require('xml-stream');

const { join } = require('path');
const envFile = require('node-env-file');

const { Client } = require('pg');
const { from: copyFrom } = require('pg-copy-streams');

const cliArgsSpec = {
  year: { type: 'number', demand: true },
  osmFile: {
    demand: true,
    type: 'string'
  },
  pg_env: {
    type: 'string',
    demand: false,
    choices: ['production', 'development'],
    default: 'development'
  }
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { osmFile, year, pg_env } = argv;

const configPath = join(
  __dirname,
  pg_env === 'production'
    ? '../../config/postgres.env.prod'
    : '../../config/postgres.env.dev'
);

envFile(configPath);

execSync(
  `psql -v YEAR=${year} -f ${join(
    __dirname,
    '../../sql/osm_ways_metadata/createOSMWaysMetadataTable.sql'
  )}`
);

(async () => {
  const client = new Client();
  await client.connect();

  await client.query(`TRUNCATE osm.ways_metadata_${year};`);

  const dbCopyStream = client.query(
    copyFrom(
      `COPY osm.ways_metadata_${year}(id, metadata) FROM STDIN WITH (FORMAT CSV)`
    )
  );

  const loadWay = d => {
    const {
      $: { id },
      tag
    } = d;

    const tags = Array.isArray(tag)
      ? tag.reduce((acc, { $: { k, v } }) => {
          acc[k] = v;
          return acc;
        }, {})
      : null;

    if (!(tags && tags.highway)) {
      return;
    }

    const metadata = JSON.stringify(tags).replace(/"/g, '""');

    const row = `"${id}","${metadata}"\n`;

    dbCopyStream.write(row);
  };

  const osmStream = createReadStream(osmFile);
  const xml = new XmlStream(osmStream);

  xml.collect('way tag');
  xml.on('endElement: way', loadWay);

  osmStream.on('end', () => {
    dbCopyStream.end();
  });

  dbCopyStream.on('end', () => {
    client.end();
  });
})();
