#!/bin/bash

set -e
set -a

if [[ -z "$YEAR" ]]; then
  echo "ERROR: You must specify the YEAR as an ENV variable."
  exit 1
fi

# Change CWD to this script's directory.
pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null


if [ "$PG_ENV" = "production" ]; then
	. ../../config/postgres.env.prod
else
	. ../../config/postgres.env.dev
fi

psql --quiet -v YEAR="$YEAR" \
  -f ../../sql/conflation_metadata/createConflationMetadataTable.sql

popd >/dev/null
