#!/bin/bash

set -e
set -a

STATE=ny

if ! [ -x "$(command -v 7za)" ]; then
  echo 'The 7za program is required to extract the RITIS shapefiles.'
  echo 'See: https://unix.stackexchange.com/a/183453'
  exit 1
fi;

if [[ -z "$YEAR" ]]; then
  (>&2 echo "ERROR: You must specify the YEAR as an ENV variable.")
  exit 1
fi

if [[ -z "$SHP_ZIP_PATH" ]]; then
  (>&2 echo "ERROR: You must specify the SHP_ZIP_PATH either an ENV variable.")
  exit 1
fi

if ! [[ -f "${SHP_ZIP_PATH}" ]]; then
  (>&2 echo "ERROR: SHP_ZIP_PATH ${SHP_ZIP_PATH} file found.")
  exit 1
fi


# Create a temporary work directory
TMP_WORK_DIR="$( mktemp -d )";

# Delete the TMP_WORK_DIR when script finishes
function finish {
  rm -rf "$TMP_WORK_DIR"
}
trap finish EXIT

# Extract the ZIP archive into a temp dir
7za e "$SHP_ZIP_PATH" -o"$TMP_WORK_DIR"

# Change to the work dir
pushd "$TMP_WORK_DIR" >/dev/null

# Change back to the previous CWD
popd >/dev/null

if [ -z "${NPMRDS_SHAPEFILE_VERSION}" ]; then
  (>&2 echo "ERROR: Unable to determine the NPMRDS_SHAPEFILE_VERSION using ogrinfo.")
  exit 1
fi

# Variables to store the new table's name and its parent table's name.
TABLE_NAME="npmrds_extended_shapefile_${YEAR}_v${NPMRDS_SHAPEFILE_VERSION}"
FULL_TABLE_NAME="\"${STATE}\".${TABLE_NAME}"

# If the table already exists, exit.
if psql -c "\d $FULL_TABLE_NAME" > /dev/null 2>&1; then
  echo "$FULL_TABLE_NAME already exists. Skipping table creation and shapefile loading."
  exit
fi

# Change CWD to this script's directory.
pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

# source the database connection config.
if [ "$PG_ENV" = "production" ]; then
	. ../../config/postgres.env.prod
else
	. ../../config/postgres.env.dev
fi

# Last chance to kill script... just in case
(>&2 echo "PostgreSQL Server: ${PGHOST}:${PGPORT}")
sleep 3

ROOT_TABLE_NAME="npmrds_extended_shapefile_${YEAR}"
FULL_ROOT_TABLE_NAME="public.${ROOT_TABLE_NAME}"

PARENT_TABLE_NAME="${ROOT_TABLE_NAME}"
FULL_PARENT_TABLE_NAME="ny.${PARENT_TABLE_NAME}"

# If the root table does not exist, create it.
if ! psql -c "\d $FULL_ROOT_TABLE_NAME" > /dev/null 2>&1; then
  psql \
    --quiet \
    -v YEAR="$YEAR" \
    -c "BEGIN;" \
    -f ../../sql/npmrds_extended_shapefile/root/createRootYearExtendedNPMRDSShapefileTable.sql \
    -c "COMMIT;"
fi

# If the parent table does not exist, create it.
if ! psql -c "\d $FULL_PARENT_TABLE_NAME" > /dev/null 2>&1; then
  psql \
    --quiet \
    -v STATE="$STATE" -v YEAR="$YEAR" \
    -c "BEGIN;" \
    -f ../../sql/npmrds_extended_shapefile/state/createStateExtendedNPMRDSShapefileYearTable.sql \
    -c "COMMIT;"
fi

# Get the absolute paths to the required SQL scripts before changing directory.
CREATE_TABLE_SQL_FILE_PATH="$(
  realpath ../../sql/npmrds_extended_shapefile/state/createStateExtendedNPMRDSShapefileYearVersionTable.sql
)"
OPTIMIZE_TABLE_SQL_FILE_PATH="$(
  realpath ../../sql/npmrds_extended_shapefile/state/optimizeExtendedStateNPMRDSShapefileYearVersionTable.sql
)"

# Create the table into which we will upload the data
psql \
  --quiet \
  -v STATE="$STATE" -v YEAR="$YEAR" -v NPMRDS_SHAPEFILE_VERSION="$NPMRDS_SHAPEFILE_VERSION" \
  -c "BEGIN;" \
  -f "${CREATE_TABLE_SQL_FILE_PATH}" \
  -c "COMMIT;"

# Upload the data
ogr2ogr -append -update -t_srs EPSG:4326 -f \
  PostgreSQL "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
  "$TMP_WORK_DIR" -nlt PROMOTE_TO_MULTI -nln "${STATE}.${TABLE_NAME}";

# Create spatial index and cluster the table using it.
psql \
  --quiet \
  -v STATE="$STATE" -v YEAR="$YEAR" -v NPMRDS_SHAPEFILE_VERSION="$NPMRDS_SHAPEFILE_VERSION" \
  -c "BEGIN;" \
  -f "${OPTIMIZE_TABLE_SQL_FILE_PATH}" \
  -c "COMMIT;" \
  -c "VACUUM ANALYZE ${FULL_TABLE_NAME};"

echo "$FULL_TABLE_NAME"

# Which table in this schema currently inherits public.npmrds_extended_shapefile_:YEAR?
#   We need this info to potentially uninherit that table, and
#   set the newly created table as the default for the YEAR.
CUR_DEFAULT="$(psql -t -c "
  SELECT c.relname
    FROM pg_inherits 
      JOIN pg_class AS c ON (inhrelid=c.oid)
      JOIN pg_class as p ON (inhparent=p.oid)
      JOIN pg_namespace pn ON pn.oid = p.relnamespace
      JOIN pg_namespace cn ON cn.oid = c.relnamespace
    WHERE (
      (pn.nspname = '${STATE}')
      AND
      (p.relname = '${PARENT_TABLE_NAME}')
    );
" | sed '/^$/d; s/^\s*//g')"

# If the newly uploaded table is a newer version than the current default version,
#   set the newly uploaded table as the default for the given state/year.
if [ -z "${CUR_DEFAULT}" ] || [[ "${TABLE_NAME}" > "${CUR_DEFAULT}" ]]; then
  if ! [ -z "${CUR_DEFAULT}" ]; then
    UNINHERIT_OLD="ALTER TABLE \"${STATE}\".${CUR_DEFAULT} NO INHERIT ${FULL_PARENT_TABLE_NAME};"
  fi
  INHERIT_NEW="ALTER TABLE ${FULL_TABLE_NAME} INHERIT ${FULL_PARENT_TABLE_NAME};"

  psql \
    --quiet \
    -c 'BEGIN;' \
    -c "$UNINHERIT_OLD" \
    -c "$INHERIT_NEW" \
    -c 'COMMIT;'

  echo "$FULL_TABLE_NAME set as the default for $FULL_PARENT_TABLE_NAME"
fi

popd >/dev/null
