#!/bin/bash

set -e

ogr2ogr \
  -f GPKG "$COMM_GPKG_PATH" \
  -nln "ris_version_a_diff_segments" \
  -oo PRELUDE_STATEMENTS="ATTACH '$VERSION_A_GPKG_PATH' AS ris_a; ATTACH '$COMM_DB_PATH' AS comm_db;" \
  -sql '
    SELECT
        GIS_ID,
        Beg_MP,
        1 AS version_exclusive,
        Shape
      FROM ris_a.roadway_inventory_system
        INNER JOIN comm_db.ris_segment_version_inclusion
          USING (GIS_ID, Beg_MP)
        WHERE ( is_in_ris_version_a AND ( NOT is_in_ris_version_b ) )

    UNION

    SELECT
        GIS_ID,
        Beg_MP,
        0 AS version_exclusive,
        Shape
      FROM ris_a.roadway_inventory_system
        INNER JOIN comm_db.ris_segment_changed_geometries
          USING (GIS_ID, Beg_MP)
    ' \
  "$VERSION_A_GPKG_PATH"

ogr2ogr \
  -f GPKG "$COMM_GPKG_PATH" \
  -append \
  -nln "ris_version_b_diff_segments" \
  -oo PRELUDE_STATEMENTS="ATTACH '$VERSION_B_GPKG_PATH' AS ris_b; ATTACH '$COMM_DB_PATH' AS comm_db;" \
  -sql '
    SELECT
        GIS_ID,
        Beg_MP,
        1 AS version_exclusive,
        Shape
      FROM ris_b.roadway_inventory_system
        INNER JOIN comm_db.ris_segment_version_inclusion
          USING (GIS_ID, Beg_MP)
        WHERE ( ( NOT is_in_ris_version_a ) AND is_in_ris_version_b )

    UNION

    SELECT
        GIS_ID,
        Beg_MP,
        0 AS version_exclusive,
        Shape
      FROM ris_b.roadway_inventory_system
        INNER JOIN comm_db.ris_segment_changed_geometries
          USING (GIS_ID, Beg_MP)
    ' \
  "$VERSION_A_GPKG_PATH"

# ===== Change GPKG file owner =====

# Because running as docker creates the GPKG as root,
#   change the owner so UID and GID match this script's owners.
USER_ID="$( stat -c '%u' "$BASH_SOURCE" )"
GROUP_ID="$( stat -c '%g' "$BASH_SOURCE" )"

chown "$USER_ID":"$GROUP_ID" "$COMM_GPKG_PATH"

