DROP TABLE IF EXISTS state_abbreviations CASCADE;

CREATE TABLE state_abbreviations (
  state_name   VARCHAR(20) PRIMARY KEY,
  abbreviation CHAR(2)
) WITH (fillfactor = 100);

INSERT INTO state_abbreviations (state_name, abbreviation)
  VALUES
    ('Alabama', 'al'),
    ('Alaska', 'ak'),
    ('Arizona', 'az'),
    ('Arkansas', 'ar'),
    ('California', 'ca'),
    ('Colorado', 'co'),
    ('Connecticut', 'ct'),
    ('Delaware', 'de'),
    ('District of Columbia', 'dc'),
    ('Florida', 'fl'),
    ('Georgia', 'ga'),
    ('Hawaii', 'hi'),
    ('Idaho', 'id'),
    ('Illinois', 'il'),
    ('Indiana', 'in'),
    ('Iowa', 'ia'),
    ('Kansas', 'ks'),
    ('Kentucky', 'ky'),
    ('Louisiana', 'la'),
    ('Maine', 'me'),
    ('Montana', 'mt'),
    ('Nebraska', 'ne'),
    ('Nevada', 'nv'),
    ('New Hampshire', 'nh'),
    ('New Jersey', 'nj'),
    ('New Mexico', 'nm'),
    ('New York', 'ny'),
    ('North Carolina', 'nc'),
    ('North Dakota', 'nd'),
    ('Ohio', 'oh'),
    ('Oklahoma', 'ok'),
    ('Oregon', 'or'),
    ('Maryland', 'md'),
    ('Massachusetts', 'ma'),
    ('Michigan', 'mi'),
    ('Minnesota', 'mn'),
    ('Mississippi', 'ms'),
    ('Missouri', 'mo'),
    ('Pennsylvania', 'pa'),
    ('Rhode Island', 'ri'),
    ('South Carolina', 'sc'),
    ('South Dakota', 'sd'),
    ('Tennessee', 'tn'),
    ('Texas', 'tx'),
    ('Utah', 'ut'),
    ('Vermont', 'vt'),
    ('Virginia', 'va'),
    ('Washington', 'wa'),
    ('West Virginia', 'wv'),
    ('Wisconsin', 'wi'),
    ('Wyoming', 'wy')
;
