#!/bin/bash

# NOTE: In some cases, the NYS RoadwayInventorySystem Geodatabase requires the ogr2ogr FileGDB driver.
#       That extension is typically not included in the official builds (apt-get).
#       A special build including FileGDB (ubuntu-full) can be created using the gdal Docker scripts.
#         See: https://github.com/OSGeo/gdal/tree/v3.3.0/gdal/docker

# NOTE: This script expects the Geodatabase to be in the Docker container's /base_data directory.
#       Output is written to the Docker container's /derived_data directory.

set -e

# ===== Create the GPKG file =====

rm -f "$GPKG_PATH"

ogr2ogr \
  -f GPKG "$GPKG_PATH" \
  -skipfailures \
  -nln "$OUTPUT_LAYER_NAME" \
  -nlt MULTILINESTRING \
  "$GDB_PATH"

# ===== Change GPKG file owner =====

# Because running as docker creates the GPKG as root,
#   change the owner so UID and GID match this script's owners.
USER_ID="$( stat -c '%u' "$BASH_SOURCE" )"
GROUP_ID="$( stat -c '%g' "$BASH_SOURCE" )"

chown "$USER_ID":"$GROUP_ID" "$GPKG_PATH"
