#!/bin/bash

HEADER="$(
  find base_data -type f -name '*.CSV' -exec head -1 {} \; |
    sed 's/\r//' |
    sort -u
)"

# https://superuser.com/a/795465
if (( $( grep -c . <<< "$HEADER" ) > 1 )); then
  echo 'ERROR: Inconsistent file headers'
  exit 1
fi


cat \
  <(
    echo "$HEADER"
  ) \
  <(
    # Output the data rows, removing the dupes
    find base_data -type f -name '*.CSV' |
      sort |
      while read -r f; do
        # shellcheck disable=SC2086
        sed 's/\r//; s/\s\{1,\}/ /g; s/"\s\{0,\}/"/g;  s/\s\{0,\}"/"/g; s/""//g; s/, /,/g; s/ ,/,/g' "$f" |
          awk 'NR>1'
      done
  ) |
  ./src/sortInputCSV |
  ./src/transform_to_standard_schema |
  ./src/loadCsvIntoDb
