#!/bin/bash

set -e
set -a

if [[ -z "$YEAR" ]]; then
  echo "ERROR: You must specify the YEAR as an ENV variable."
  exit 1
fi

if [[ -z "$RIS_GEODATABASE_ZIP" ]]; then
  echo "ERROR: You must specify the RIS_GEODATABASE_ZIP as an ENV variable."
  exit 1
fi

RIS_GEODATABASE_ZIP="$( realpath "$RIS_GEODATABASE_ZIP" )"

if [ ! -f "$RIS_GEODATABASE_ZIP" ]; then
  (>&2 echo "ERROR: RIS_GEODATABASE_ZIP not found at $RIS_GEODATABASE_ZIP")
  exit 1
fi

# Change CWD to this script's directory.
pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null


if [ "$PG_ENV" = "production" ]; then
	. ../../../config/postgres.env.prod
else
	. ../../../config/postgres.env.dev
fi

# Last chance to kill script... just in case
(>&2 echo "PostgreSQL Server: ${PGHOST}:${PGPORT}")
sleep 3

TABLE_NAME="ris.road_inventory_system_$YEAR"

psql --quiet \
  -v YEAR="$YEAR" \
  -f ../../../sql/ris/createRoadInventorySystemTables.sql \
  -c "TRUNCATE $TABLE_NAME;"

# Upload the data
ogr2ogr -overwrite -append -preserve_fid -t_srs EPSG:4326 \
  -f PostgreSQL \
    "PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}" \
    "/vsizip/$RIS_GEODATABASE_ZIP" -preserve_fid -nlt MULTILINESTRING -dim 2 -nln "$TABLE_NAME";

psql --quiet \
  -c "CLUSTER $TABLE_NAME;" \
  -c "ANALYZE $TABLE_NAME;"

popd >/dev/null
