import { TranscomEventCategory } from "../../types";

const { ACCIDENT: A, CONSTRUCTION: C, OTHER: O } = TranscomEventCategory;

export default {
  "3rd rail problem": O,
  "3rd rail repairs": O,
  "accident investigation": A,
  "accident road closed": A,
  "accident with injuries": A,
  "accident with property damage": A,
  accident: A,
  "additional service": O,
  airshow: O,
  "amber alert": O,
  "animal on tracks": O,
  "attenuator repairs": C,
  "automobile on the tracks": O,
  "awards ceremony": O,
  "barrier repairs": C,
  "baseball game": O,
  "basketball game": O,
  "bicycle event": O,
  "bicycle race": O,
  blackout: O,
  "boxing match": O,
  boxing: O,
  "brakes in emergency": O,
  "bridge cable repairs": C,
  "bridge construction": C,
  "bridge demolition work": O,
  "bridge demolition": C,
  "bridge inspection": C,
  "bridge maintenance operations": C,
  "bridge painting": C,
  "bridge rehabilitation": C,
  "bridge replacement": C,
  "bridge work": C,
  "broken crossing gate": O,
  "broken rail repairs": O,
  "broken rail": O,
  "brush fire": O,
  "building collapse": O,
  "building fire": O,
  "bus fire": A,
  "capacity related": O,
  "cargo spill": O,
  carnival: O,
  "cctv repairs": C,
  "christmas spectacular": O,
  "christmas tree lighting": O,
  circus: O,
  "cold weather": O,
  "collapsed manhole": O,
  "collapsed scaffolding": O,
  "collapsed sewer grate": O,
  concert: O,
  "concrete tie replacement": O,
  congestion: O,
  "construction cancelled": C,
  "construction embargo": C,
  construction: C,
  "crack sealing": C,
  "crane operations": C,
  "crossing gate malfunction": O,
  "crossing grade repairs": O,
  crowd: O,
  "culvert repairs": C,
  "curb work": C,
  "dark station": O,
  "debris on tracks": O,
  "debris spill": O,
  "deck work": C,
  delays: O,
  demonstration: O,
  derailment: O,
  "disabled bus": A,
  "disabled tractor trailer": A,
  "disabled train": O,
  "disabled truck": A,
  "disabled vehicle": A,
  "downed pole": O,
  "downed tree": O,
  "downed wires": O,
  "drainage improvements": C,
  "drawbridge open": O,
  "drawbridge testing": C,
  "earlier derailment": O,
  "earlier equipment problems": O,
  "earlier fire department activity": O,
  "earlier flooding": O,
  "earlier incident": A,
  "earlier overhead wire problems": O,
  "earlier police department activity": O,
  "earlier power problems": O,
  "earlier signal problems": O,
  "electrical repairs": O,
  "electronic toll lane repairs": C,
  "elevator malfunction": O,
  "elevator work": O,
  "emergency construction": C,
  "emergency maintenance": O,
  "emergency repairs": C,
  "emergency track work": O,
  "ems activity": O,
  "equipment malfunction": O,
  "equipment problems": O,
  "escalator malfunction": O,
  "escalator work": O,
  exhibition: O,
  "expansion joint repairs": C,
  "extra service": O,
  "ez-pass toll lane repairs": O,
  fair: O,
  "falling debris": O,
  "falling ice": O,
  "fence repairs": C,
  festival: O,
  "fire department activity": O,
  "fireworks display": O,
  fireworks: O,
  "fleet week": O,
  flooding: O,
  "fluid spill": O,
  fog: O,
  "football game": O,
  "fuel spill": O,
  "funeral procession": O,
  funeral: O,
  "gas leak": O,
  "gas main break": O,
  "gas main repairs": C,
  "gas main work": C,
  "general work order": O,
  "golf tournament": O,
  "graduation ceremonies": O,
  "gridlock alert day": O,
  "guard rail repairs": C,
  "hazmat spill": O,
  "heavy snow": O,
  "heavy traffic": O,
  "high winds": O,
  "hockey game": O,
  "holiday schedule": O,
  "holiday weekend": O,
  holiday: O,
  "hov rules": O,
  ice: O,
  "icicle removal": C,
  icing: O,
  "injured customer": O,
  "installation of conduits": C,
  "installation of fiber optics": C,
  "installation of sign structure": C,
  "installation of traffic management systems": C,
  "installation of traffic monitoring systems": C,
  "intersection improvements": C,
  "jack-knifed tractor trailer": A,
  "job action": O,
  "kids show/performance": O,
  "known other": O,
  landslide: O,
  "late running construction": O,
  "line striping": C,
  "long term road construction": C,
  "longterm construction": C,
  "malfunctioning traffic light": O,
  marathon: O,
  march: O,
  "memorial service": O,
  "midday roadwork": O,
  milling: C,
  "minor delays": O,
  "misplaced bus": O,
  "misplaced commercial vehicle": O,
  "misplaced tractor trailer": A,
  "missing manhole cover": O,
  "missing sewer grate": O,
  "motor vehicle accident": O,
  "motorcycle rally": O,
  "moveable barrier repairs": C,
  "movie filming": O,
  "movie/tv filming": O,
  "moving operation": C,
  mowing: C,
  "nearby building collapse": O,
  "new traffic pattern": O,
  "new years celebration": O,
  "new years eve": O,
  "nfl draft": O,
  "no fuel available": O,
  "no water available": O,
  "noise wall construction": C,
  "off-peak roadwork": C,
  "open drawbridge": O,
  "operational activity": O,
  "ops sail": O,
  "other special event": O,
  other: O,
  "outdoor market": O,
  "outside agency assist": O,
  overcrowding: O,
  "overhead sign repair": C,
  "overheight tractor trailer": A,
  "overnight roadwork": C,
  "overpass repairs": O,
  "overturned dump truck": A,
  "overturned tractor trailer": A,
  "overturned truck": A,
  "overturned vehicle": A,
  "ozone alert": O,
  parade: O,
  "parking related": O,
  "passenger demand": O,
  "paving operations": C,
  "pedestrian accident": A,
  "performing arts": O,
  "person struck by train": O,
  "person under train": O,
  "planned demonstration": O,
  "plate repairs": C,
  "platform repairs": O,
  "play/show": O,
  "plowing and salting": C,
  "pockets of volume": O,
  "police activity": O,
  "police department activity": O,
  "police operational activity": O,
  "pothole repair": C,
  "pothole repairs": C,
  "power failure": O,
  "power problem": O,
  "power problems": O,
  "presidential visit": O,
  procession: O,
  "race event": O,
  race: O,
  racing: O,
  rally: O,
  reconstruction: C,
  renovation: C,
  repairs: O,
  repaving: C,
  "road collapse": O,
  "road maintenance operations": C,
  "road rehabilitation": C,
  "road sweeping": O,
  "road widening": C,
  "roadway non-hazmat spill": O,
  roadwork: C,
  "rock blasting": O,
  rodeo: O,
  "roller derby": O,
  "rough road": O,
  "roving repairs": C,
  "rubbernecking delays": O,
  "safety improvements": C,
  "sagging wires": O,
  "schedule modification": O,
  "scheduled roadwork": C,
  "security check point": O,
  "separated tractor trailer": O,
  "sewer collapse": O,
  "sewer main break": O,
  "shifted plates": O,
  show: O,
  "sick customer": O,
  "sign work": C,
  "signal problem": O,
  "signal problems": O,
  "signal repairs": O,
  sinkhole: O,
  "skating event": O,
  skating: O,
  "smoke condition": O,
  "snow removal": O,
  "soccer game": O,
  "special event": O,
  "speed restriction": O,
  spinout: A,
  "split tractor trailer": A,
  "sports event": O,
  "stalled train": O,
  "stalled work train": O,
  "station rehabilitation": O,
  "station renovations": O,
  "steam leak": O,
  "steel repairs": C,
  "stop and go traffic": O,
  "street fair": O,
  "street light knockdown": O,
  "street sweeping": C,
  "structure repairs": C,
  "stuck drawbridge": O,
  "substructure repairs": C,
  "sun glare": O,
  "survey work": C,
  "switch problems": O,
  "switch repairs": O,
  "tennis tournament": O,
  "test message": O,
  "toll lane repairs": C,
  "toll plaza repairs": C,
  "track and field event": O,
  "track condition": O,
  "track fire": O,
  "track repairs": O,
  "track replacement": O,
  "track washout": O,
  "track work": O,
  "tractor trailer fire": A,
  "trade expo": O,
  "traffic congestion": O,
  "traffic shift": C,
  "traffic signal repairs": C,
  "train car fire": O,
  "transformer fire": O,
  "transit related incident": A,
  "tree trimming": C,
  "trespasser struck": O,
  "truck fire": A,
  "truck restrictions": O,
  "tunnel repairs": C,
  "tunnel washing": C,
  "unanticipated construction delay": C,
  "unknown other": O,
  "unplanned demonstration": O,
  "utility work": C,
  "vehicle fire": A,
  "vehicle on the tracks": O,
  "vip visit": O,
  "vms repairs": C,
  "water main work": C,
  "watermain break repairs": C,
  "watermain break": O,
  "weather related equipment problems": O,
  "weather related switch problems": O,
  "weather related track problems": O,
  "weather related": O,
  "weekday schedule": O,
  "weekend construction": C,
  "weekend long construction": C,
  "wet pavement": O,
  "wide load": O,
  "wrestling match": O,
  wrestling: O,
};
