-- Subset of the npmrds_shapefile_:YEAR columns
CREATE TABLE public.tmc_identification_:YEAR (
  tmc                      CHARACTER VARYING,
  type                     CHARACTER VARYING,
  road                     CHARACTER VARYING,
  road_order               REAL,
  intersection             CHARACTER VARYING,
  tmclinear                BIGINT,
  country                  CHARACTER VARYING,
  state                    CHARACTER VARYING,
  county                   CHARACTER VARYING,
  zip                      CHARACTER VARYING,
  direction                CHARACTER VARYING,
  start_latitude           DOUBLE PRECISION,
  start_longitude          DOUBLE PRECISION,
  end_latitude             DOUBLE PRECISION,
  end_longitude            DOUBLE PRECISION,
  miles                    DOUBLE PRECISION,
  frc                      BIGINT,
  border_set               CHARACTER VARYING,
  isprimary                SMALLINT,
  f_system                 BIGINT,
  urban_code               BIGINT,
  faciltype                BIGINT,
  structype                BIGINT,
  thrulanes                BIGINT,
  route_numb               BIGINT,
  route_sign               BIGINT,
  route_qual               BIGINT,
  altrtename               CHARACTER VARYING,
  aadt                     BIGINT,
  aadt_singl               BIGINT,
  aadt_combi               BIGINT,
  nhs                      BIGINT,
  nhs_pct                  BIGINT,
  strhnt_typ               BIGINT,
  strhnt_pct               BIGINT,
  truck                    BIGINT,
  timezone_name            CHARACTER VARYING,
	active_start_date        DATE,
	active_end_date					 DATE,
  download_timestamp 			 TIMESTAMP
);
