#!/usr/bin/env node

// FIXME: If osm version tables did not exists, drop them if the loader fails
//        so we don't leave behind empty tables.

// https://wiki.openstreetmap.org/wiki/Way#Examples
//   The nodes defining the geometry of the way are enumerated in the correct order,
//     and indicated only by reference using their unique identifier.
//   These nodes must have been already defined separately with their coordinates.
//
// https://wiki.openstreetmap.org/wiki/Relation:restriction

const { execSync } = require("child_process");
const { createReadStream } = require("fs");

const yargs = require("yargs");
const XmlStream = require("xml-stream");

const { join } = require("path");
const envFile = require("node-env-file");

const { Pool } = require("pg");
const { from: copyFrom } = require("pg-copy-streams");

const _ = require("lodash");

const cliArgsSpec = {
  osmVersion: { type: "string", demand: true },
  osmXmlFile: {
    demand: true,
    type: "string",
  },
  pg_env: {
    type: "string",
    demand: false,
    choices: ["production", "development"],
    default: "development",
  },
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    "camel-case-expansion": false,
    "flatten-duplicate-arrays": false,
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { osmVersion, osmXmlFile, pg_env } = argv;

const configPath = join(
  __dirname,
  pg_env === "production"
    ? "../../../config/postgres.env.prod"
    : "../../../config/postgres.env.dev"
);

envFile(configPath);

const dbConnectionPool = new Pool();

const OSM_SCHEMA = "osm";

const OSM_NODES_TABLE_NAME = `osm_nodes_v${osmVersion}`;
const OSM_NODES_TABLE_FULL_NAME = `${OSM_SCHEMA}.${OSM_NODES_TABLE_NAME}`;
const TEMP_NODES_TABLE_FULL_NAME = `${OSM_SCHEMA}.tmp_${OSM_NODES_TABLE_NAME}`;

const OSM_WAYS_TABLE_NAME = `osm_ways_v${osmVersion}`;
const OSM_WAYS_TABLE_FULL_NAME = `${OSM_SCHEMA}.${OSM_WAYS_TABLE_NAME}`;
const TEMP_WAYS_TABLE_FULL_NAME = `${OSM_SCHEMA}.tmp_${OSM_WAYS_TABLE_NAME}`;

const OSM_RELATIONS_TABLE_NAME = `osm_relations_v${osmVersion}`;
const OSM_RESTRICTIONS_VIEW_NAME = `osm_restrictions_v${osmVersion}`;
const OSM_RELATIONS_TABLE_FULL_NAME = `${OSM_SCHEMA}.${OSM_RELATIONS_TABLE_NAME}`;
const OSM_RESTRICIONS_VIEW_FULL_NAME = `${OSM_SCHEMA}.${OSM_RESTRICTIONS_VIEW_NAME}`;
const TEMP_RELATIONS_TABLE_FULL_NAME = `${OSM_SCHEMA}.tmp_${OSM_RELATIONS_TABLE_NAME}`;

console.log(OSM_NODES_TABLE_FULL_NAME);
console.log(OSM_WAYS_TABLE_FULL_NAME);

const createNodesTableSqlPath = join(
  __dirname,
  "../../../sql/osm/create_versioned_osm_nodes_tables.sql"
);
const createWaysTableSqlPath = join(
  __dirname,
  "../../../sql/osm/create_versioned_osm_ways_tables.sql"
);

const createRoadsViewSqlPath = join(
  __dirname,
  "../../../sql/osm/create_osm_roads_view.sql"
);

const createRelationsTableSqlPath = join(
  __dirname,
  "../../../sql/osm/create_versioned_osm_relations_tables.sql"
);

const createRestrictionsViewSqlPath = join(
  __dirname,
  "../../../sql/osm/create_versioned_osm_restrictions_view.sql"
);

async function queryOsmTableVersionsExistence(dbConn) {
  const [
    nodesTableExistsResult,
    waysTableExistsResult,
    relationsTableExistsResult,
  ] = await Promise.all([
    dbConn.query(`
      SELECT EXISTS (
        SELECT
          FROM information_schema.tables
          WHERE (
            ( table_schema = '${OSM_SCHEMA}' )
            AND
            ( table_name = '${OSM_NODES_TABLE_NAME}' )
          )
      ) ;
    `),
    dbConn.query(`
      SELECT EXISTS (
        SELECT
          FROM information_schema.tables
          WHERE (
            ( table_schema = '${OSM_SCHEMA}' )
            AND
            ( table_name = '${OSM_WAYS_TABLE_NAME}' )
          )
      ) ;
    `),
    dbConn.query(`
      SELECT EXISTS (
        SELECT
          FROM information_schema.tables
          WHERE (
            ( table_schema = '${OSM_SCHEMA}' )
            AND
            ( table_name = '${OSM_RELATIONS_TABLE_NAME}' )
          )
      ) ;
    `),
  ]);

  return {
    nodesTableExists: nodesTableExistsResult.rows[0].exists,
    waysTableExists: waysTableExistsResult.rows[0].exists,
    relationsTableExists: relationsTableExistsResult.rows[0].exists,
  };
}

// TODO: If tables do not already exists, DROP them if loading fails.
async function createOsmVersionTables(dbConn) {
  const { nodesTableExists, waysTableExists, relationsTableExists } =
    await queryOsmTableVersionsExistence(dbConn);

  if (nodesTableExists && waysTableExists && relationsTableExists) {
    return;
  }

  if (
    (nodesTableExists || waysTableExists || relationsTableExists) &&
    !(nodesTableExists && waysTableExists && relationsTableExists)
  ) {
    throw new Error(
      `ERROR: Database in inconsistent state.
          nodesTableExists:     ${nodesTableExists}
          waysTableExists:      ${waysTableExists}
          relationsTableExists  ${relationsTableExists}\n`
    );
  }

  try {
    execSync(
      `psql -v OSM_VERSION=${osmVersion} -f '${createNodesTableSqlPath}'`
    );

    execSync(
      `psql -v OSM_VERSION=${osmVersion} -f '${createWaysTableSqlPath}'`
    );

    execSync(
      `psql -v OSM_VERSION=${osmVersion} -f '${createRoadsViewSqlPath}'`
    );

    execSync(
      `psql -v OSM_VERSION=${osmVersion} -f '${createRelationsTableSqlPath}'`
    );

    execSync(
      `psql -v OSM_VERSION=${osmVersion} -f '${createRestrictionsViewSqlPath}'`
    );
  } catch (err) {
    dbConn.query(`
      BEGIN;

      DROP TABLE IF EXISTS ${OSM_NODES_TABLE_FULL_NAME} CASCADE;
      DROP TABLE IF EXISTS ${OSM_WAYS_TABLE_FULL_NAME} CASCADE;
      DROP TABLE IF EXISTS ${OSM_RELATIONS_TABLE_FULL_NAME} CASCADE;
      DROP MATERIALIZED VIEW IF EXISTS ${OSM_RESTRICIONS_VIEW_FULL_NAME};

      COMMIT;
    `);

    throw err;
  }

  const verifiedTableExistence = await queryOsmTableVersionsExistence(dbConn);

  if (
    !(
      verifiedTableExistence.nodesTableExists &&
      verifiedTableExistence.waysTableExists &&
      verifiedTableExistence.relationsTableExists
    )
  ) {
    throw new Error(
      "ERROR: DDL scripts failed to create tables with the expected table."
    );
  }
}

let nodeNum = 0;
let wayNum = 0;
let relationNum = 0;

function initNodeHandler(xml, nodesCopyStream) {
  xml.collect("node tag");
  xml.on("endElement: node", async (d) => {
    const {
      $: { id: osmNodeId, lat, lon },
      tag,
    } = d;

    const tags = Array.isArray(tag)
      ? tag.reduce((acc, { $: { k, v } }) => {
          acc[k] = v;
          return acc;
        }, {})
      : null;

    const escapedTags = tags
      ? `"${JSON.stringify(tags).replace(/"/g, '""')}"`
      : "";

    const row = `"${+osmNodeId}",${escapedTags},"SRID=4326;POINT(${lon} ${lat})"\n`;

    const good = nodesCopyStream.write(row);

    if (!good) {
      xml.pause();
      await new Promise((resolve) => nodesCopyStream.once("drain", resolve));
      xml.resume();
    }

    console.log("node #", ++nodeNum);
  });
}

function initWayHandler(xml, waysCopyStream) {
  xml.collect("way nd");
  xml.collect("way tag");
  xml.on("endElement: way", async (d) => {
    const {
      $: { id: osmWayId },
      nd,
      tag,
    } = d;

    const osmNodeIds = Array.isArray(nd)
      ? nd.map(({ $: { ref } }) => +ref)
      : null;

    const tags = Array.isArray(tag)
      ? tag.reduce((acc, { $: { k, v } }) => {
          acc[k] = v;
          return acc;
        }, {})
      : null;

    const escapedTags = tags ? JSON.stringify(tags).replace(/"/g, '""') : "";

    const row = `"${osmWayId}","${escapedTags}","{${osmNodeIds}}"\n`;

    const good = waysCopyStream.write(row);

    if (!good) {
      xml.pause();
      await new Promise((resolve) => waysCopyStream.once("drain", resolve));
      xml.resume();
    }

    console.log("way #", ++wayNum);
  });
}

function initRelationHandler(xml, relationsCopyStream) {
  xml.collect("relation nd");
  xml.collect("relation member");
  xml.collect("relation tag");

  xml.on("endElement: relation", async (d) => {
    const {
      $: { id: osmRelationId },
      tag,
      member,
    } = d;

    const tags = Array.isArray(tag)
      ? tag.reduce((acc, { $: { k, v } }) => {
          acc[k] = v;
          return acc;
        }, {})
      : null;

    const members = _(member)
      .map(({ $ }) => $)
      .sortBy("role")
      .value();

    const escapedTags = tags ? JSON.stringify(tags).replace(/"/g, '""') : "";
    const escapedMembers = members
      ? JSON.stringify(members).replace(/"/g, '""')
      : "";

    const row = `"${osmRelationId}","${escapedTags}","${escapedMembers}"\n`;

    const good = relationsCopyStream.write(row);

    if (!good) {
      xml.pause();
      await new Promise((resolve) =>
        relationsCopyStream.once("drain", resolve)
      );
      xml.resume();
    }

    console.log("restriction #", ++relationNum);
  });
}

async function finish(dbConn) {
  console.time("load nodes");
  await dbConn.query(`
    BEGIN;

    CREATE OR REPLACE FUNCTION pg_temp.tmp_json_or_null(TEXT, BIGINT, TEXT)
      RETURNS JSONB LANGUAGE PLPGSQL IMMUTABLE AS $$
    BEGIN
          RETURN $3::JSONB;
      EXCEPTION
          WHEN OTHERS THEN
            RAISE NOTICE 'INVALID JSON FOR OSM % %', $1, $2;
            RETURN NULL;
    END $$;

    DELETE FROM ${OSM_NODES_TABLE_FULL_NAME} ;

    INSERT INTO ${OSM_NODES_TABLE_FULL_NAME} (
      id,
      tags,
      wkb_geometry
    )
      SELECT
          id,
          pg_temp.tmp_json_or_null('NODE'::TEXT, id, tags) AS tags,
          public.ST_GeomFromEWKT(wkb_geometry) AS wkb_geometry
        FROM ${TEMP_NODES_TABLE_FULL_NAME} ;

    CLUSTER ${OSM_NODES_TABLE_FULL_NAME} ;
  `);
  console.timeEnd("load nodes");

  console.time("load ways");
  await dbConn.query(`
    DELETE FROM ${OSM_WAYS_TABLE_FULL_NAME} ;

    INSERT INTO ${OSM_WAYS_TABLE_FULL_NAME} (
      id,
      tags,
      node_ids,
      wkb_geometry
    )
      SELECT
          id,
          pg_temp.tmp_json_or_null('WAY'::TEXT, id, tags) AS tags,
          node_ids,
          b.wkb_geometry
        FROM ${TEMP_WAYS_TABLE_FULL_NAME} AS a
          INNER JOIN (
              SELECT
                  a.id,
                  ST_MakeLine(c.wkb_geometry ORDER BY pt_idx) AS wkb_geometry
                FROM ${TEMP_WAYS_TABLE_FULL_NAME} AS a
                  JOIN LATERAL UNNEST(node_ids) WITH ORDINALITY AS b(pt_id, pt_idx)
                    ON true
                  INNER JOIN ${OSM_NODES_TABLE_FULL_NAME} AS c
                    ON ( b.pt_id = c.id )
                GROUP BY 1
            ) AS b
            USING (id)
    ;

    CLUSTER ${OSM_WAYS_TABLE_FULL_NAME} ;

    COMMIT;
  `);
  console.timeEnd("load ways");

  console.time("load relations");
  await dbConn.query(`
    DELETE FROM ${OSM_RELATIONS_TABLE_FULL_NAME} ;

    INSERT INTO ${OSM_RELATIONS_TABLE_FULL_NAME} (
      id,
      tags,
      members
    )
      SELECT
          id,
          pg_temp.tmp_json_or_null('RELATION TAG'::TEXT, id, tags) AS tags,
          pg_temp.tmp_json_or_null('RELATION MEMBER'::TEXT, id, members) AS members
        FROM ${TEMP_RELATIONS_TABLE_FULL_NAME}
    ;

    CLUSTER ${OSM_RELATIONS_TABLE_FULL_NAME} ;

    REFRESH MATERIALIZED VIEW ${OSM_RESTRICIONS_VIEW_FULL_NAME} ;

    COMMIT;
  `);
  console.timeEnd("load relations");
}

(async () => {
  const nodesClient = await dbConnectionPool.connect();
  const waysClient = await dbConnectionPool.connect();
  const relationsClient = await dbConnectionPool.connect();

  try {
    await createOsmVersionTables(nodesClient);

    await Promise.all([
      nodesClient.query(`
        BEGIN;

        CREATE TABLE ${TEMP_NODES_TABLE_FULL_NAME} (
          LIKE ${OSM_NODES_TABLE_FULL_NAME}
        );

        -- Change the column types to TEXT for easier loading.
        ALTER TABLE ${TEMP_NODES_TABLE_FULL_NAME}
          ALTER COLUMN tags TYPE TEXT,
          ALTER COLUMN wkb_geometry TYPE TEXT
        ;
      `),

      waysClient.query(`
        BEGIN;

        CREATE TABLE ${TEMP_WAYS_TABLE_FULL_NAME} (
          LIKE ${OSM_WAYS_TABLE_FULL_NAME}
        );

        -- Change the column type to TEXT for easier loading.
        ALTER TABLE ${TEMP_WAYS_TABLE_FULL_NAME}
          ALTER COLUMN tags TYPE TEXT
        ;
      `),

      relationsClient.query(`
        BEGIN;

        CREATE TABLE ${TEMP_RELATIONS_TABLE_FULL_NAME} (
          LIKE ${OSM_RELATIONS_TABLE_FULL_NAME}
        );

        -- Change the column type to TEXT for easier loading.
        ALTER TABLE ${TEMP_RELATIONS_TABLE_FULL_NAME}
          ALTER COLUMN tags TYPE TEXT
        ;

        ALTER TABLE ${TEMP_RELATIONS_TABLE_FULL_NAME}
          ALTER COLUMN members TYPE TEXT
        ;
      `),
    ]);

    const nodesCopyStream = nodesClient.query(
      copyFrom(
        `COPY ${TEMP_NODES_TABLE_FULL_NAME}(id, tags, wkb_geometry) FROM STDIN WITH (FORMAT CSV)`
      )
    );

    const waysCopyStream = waysClient.query(
      copyFrom(
        `COPY ${TEMP_WAYS_TABLE_FULL_NAME}(id, tags, node_ids) FROM STDIN WITH (FORMAT CSV)`
      )
    );

    const relationsCopyStream = relationsClient.query(
      copyFrom(
        `COPY ${TEMP_RELATIONS_TABLE_FULL_NAME}(id, tags, members) FROM STDIN WITH (FORMAT CSV)`
      )
    );

    let streamClosed;
    let streamError;

    const sentinel = new Promise((resolve, reject) => {
      streamClosed = resolve;
      streamError = reject;
    });

    const xml = await new XmlStream(
      createReadStream(osmXmlFile)
        .on("close", streamClosed)
        .on("error", streamError)
    );

    initNodeHandler(xml, nodesCopyStream);
    initWayHandler(xml, waysCopyStream);
    initRelationHandler(xml, relationsCopyStream);

    let finishDone;
    let finishErr;

    const finished = new Promise((resolve, reject) => {
      finishDone = resolve;
      finishErr = reject;
    });

    xml.on("end", async () => {
      try {
        console.log("File load complete.");
        console.log(`  Inserted ${nodeNum} nodes and ${wayNum} ways.`);
        console.log("Altering columns and indexing tables.");

        await Promise.all([
          nodesCopyStream.end(),
          waysCopyStream.end(),
          relationsCopyStream.end(),
        ]);

        finishDone();
      } catch (err) {
        finishErr(err);
      }
    });

    await sentinel;
    await finished;

    await Promise.all([
      nodesClient.query("COMMIT;"),
      waysClient.query("COMMIT;"),
      relationsClient.query("COMMIT;"),
    ]);

    waysClient.release();
    relationsClient.release();
    await finish(nodesClient);
  } catch (err) {
    console.error(err);

    await Promise.all([
      nodesClient.query("ROLLBACK;"),
      waysClient.query("ROLLBACK;"),
    ]);
  } finally {
    await nodesClient.query(`
      DROP TABLE IF EXISTS ${TEMP_NODES_TABLE_FULL_NAME} ;
      DROP TABLE IF EXISTS ${TEMP_WAYS_TABLE_FULL_NAME} ;
      DROP TABLE IF EXISTS ${TEMP_RELATIONS_TABLE_FULL_NAME} ;
    `);

    nodesClient.release();

    await dbConnectionPool.end();
  }
})();
