#!/usr/bin/env node

const { execSync } = require("child_process");
const { join } = require("path");

const yargs = require("yargs");
const envFile = require("node-env-file");
const _ = require("lodash");

const { Client } = require("pg");

const ConflationMapDatabaseObjectNames = require("./ConflationMapDatabaseObjectNames");

const createConflationMapVersionDatabaseTableDdlPath = join(
  __dirname,
  "../../../sql/conflation_map/createConflationMapTable.sql"
);

const cliArgsSpec = {
  year: {
    demand: true,
    type: "number",
  },
  conflationMapVersion: {
    demand: true,
    type: "string",
    describe: "E.G.: 0.4.2",
  },
  conflationMapShapefile: {
    demand: true,
    type: "string",
  },
  pg_env: {
    type: "string",
    demand: false,
    choices: ["production", "development"],
    default: "development",
  },
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    "camel-case-expansion": false,
    "flatten-duplicate-arrays": false,
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { year, conflationMapVersion, conflationMapShapefile, pg_env } = argv;

const configPath = join(
  __dirname,
  pg_env === "production"
    ? "../../../config/postgres.env.prod"
    : "../../../config/postgres.env.dev"
);
envFile(configPath);

try {
  ConflationMapDatabaseObjectNames.validateConflationMapVersion(
    conflationMapVersion
  );
} catch (err) {
  console.error(err.message);
  process.exit(1);
}

const {
  conflationSchema,
  conflationMapTableName,
  conflationMapTableFullName,
  conflationMapTableGeometryIdxName,
  conflationMapTableGeometryIdxFullName,
} = new ConflationMapDatabaseObjectNames(year, conflationMapVersion);

const timestamp = Math.floor(new Date().getTime() / 1000);

// "TEMPORARY" table name
const tmpVersionedConflationMapTableName = `tmp_${conflationMapTableName}_${timestamp}`;
const tmpVersionedConflationMapTableFullName = `${conflationSchema}.${tmpVersionedConflationMapTableName}`;

const { PGHOST, PGPORT, PGUSER, PGDATABASE, PGPASSWORD } = process.env;

if (_.isNil(PGHOST && PGPORT && PGUSER && PGDATABASE && PGPASSWORD)) {
  console.error(
    "The PostgreSQL config file must contain the following credential variables:"
  );
  console.error("     PGHOST, PGPORT, PGUSER, PGDATABASE, PGPASSWORD");
  process.exit(1);
}

const createConflationMapVersionDatabaseTable = () => {
  // Using psql so we can use script variables.
  execSync(
    `
      psql \
        --quiet \
        -v YEAR=${year} \
        -v SCHEMA_NAME='${conflationSchema}' \
        -v TABLE_NAME='${conflationMapTableName}' \
        -v FULL_TABLE_NAME='${conflationMapTableFullName}' \
        -v GEOM_IDX_NAME='${conflationMapTableGeometryIdxName}' \
        -v FULL_GEOM_IDX_NAME='${conflationMapTableGeometryIdxFullName}' \
        -f '${createConflationMapVersionDatabaseTableDdlPath}'
    `,
    {
      // env: Object.assign({}, process.env, {
      // PGOPTIONS: '--client-min-messages=error'
      // }),
      shell: "/bin/sh",
    }
  );
};

const loadConflationMapShapefileIntoTemporaryTable = () => {
  console.log(
    `Loading shapefile into temporary table ${tmpVersionedConflationMapTableFullName}`
  );

  // Was unable to get ogr2ogr to use the id field in the shapefile for the id column in the database.
  //   Work-around I went is to let ogr2ogr create the table before loading the shapefile.
  //   It creates an ogc_fid column for the PRIMARY KEY. We ignore this column when loading the conflation_map table.
  execSync(`
    ogr2ogr -s_srs EPSG:4326 -t_srs EPSG:4326 \
      -f PostgreSQL \
        'PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}' \
      '${conflationMapShapefile}' -nln '${tmpVersionedConflationMapTableFullName}'
  `);

  // execSync(`
  // ogr2ogr -s_srs EPSG:4326 -t_srs EPSG:4326 \
  // -f PostgreSQL \
  // 'PG:host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${PGDATABASE} password=${PGPASSWORD}' \
  // '${conflationMapShapefile}' -nln '${tmpVersionedConflationMapTableFullName}'
  // `);
};

const integrateNewMapIntoDatabase = async (client) => {
  const sql = `
    BEGIN ;

    -- Clear the conflation map table, in case it already existed and has data
    DELETE FROM ${conflationMapTableFullName} ;

    -- Transfer the conflation map data from the temp to the permanent table.
    INSERT INTO ${conflationMapTableFullName} (
      id,
      dir,
      n,
      osm,
      osm_fwd,
      ris,
      tmc,
      wkb_geometry
    )
      SELECT
          id,
          dir,
          n,
          osm,
          osm_fwd,
          ris,
          tmc,
          wkb_geometry
        FROM ${tmpVersionedConflationMapTableFullName}
    ;

    -- NOTE: tmpVersionedConflationMapTable is DROPPED below in the finally clause.

    CLUSTER ${conflationMapTableFullName} ;

    COMMIT ;
  
    ANALYZE ${conflationMapTableFullName};
  `;

  return client.query(sql);
};

(async () => {
  const client = new Client();
  await client.connect();

  try {
    await client.query("BEGIN;");
    createConflationMapVersionDatabaseTable();

    let task = "load conflation map shapefile into temporary table";
    console.time(task);
    await loadConflationMapShapefileIntoTemporaryTable(client);
    console.timeEnd(task);

    task = "integrate new conflation map into database";
    console.time(task);
    await integrateNewMapIntoDatabase(client);
    console.timeEnd(task);

    await client.query("COMMIT;");
  } catch (err) {
    await client.query("ROLLBACK");
    console.error(err);
  } finally {
    try {
      // await client.query(
      // `DROP TABLE IF EXISTS ${tmpVersionedConflationMapTableFullName} ;`
      // );
    } catch (err2) {
      console.error(err2);
    }
    client.end();
  }
})();
