#!/usr/bin/env node

const { join } = require('path');

const yargs = require('yargs');
const envFile = require('node-env-file');

const { Client } = require('pg');

const {
  conflationSchema,
  conflationMapTablePrefix
} = require('./ConflationMapDatabaseObjectNames');

const getUpdateConflationMapToTranscomEventsJoinTableSql = require('./getUpdateConflationMapToTranscomEventsJoinTableSql');

const cliArgsSpec = {
  pg_env: {
    type: 'string',
    demand: false,
    choices: ['production', 'development'],
    default: 'development'
  }
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { pg_env } = argv;

const configPath = join(
  __dirname,
  pg_env === 'production'
    ? '../../../config/postgres.env.prod'
    : '../../../config/postgres.env.dev'
);
envFile(configPath);

const listLoadedConflationMapVersions = async client => {
  const sql = `
    SELECT
        TRIM(
          REPLACE(
            REPLACE(
              tablename,
              '${conflationMapTablePrefix}',
              ''
            ),
            '_',
            '.'
          )
        ) AS "conflationMapVersion"
      FROM pg_tables
      WHERE (
        ( schemaname = '${conflationSchema}' )
        AND
        ( tablename ~ '^${conflationMapTablePrefix}\\d{1,}_\\d{1,}_\\d{1,}$' )
      ) ;
  `;

  const { rows } = await client.query(sql);

  return Array.isArray(rows) && rows.length
    ? rows.map(({ conflationMapVersion }) => conflationMapVersion)
    : null;
};

const updateJoinTables = async (client, conflationMapVersions) =>
  Promise.all(
    conflationMapVersions.map(async conflationMapVersion => {
      const sql = getUpdateConflationMapToTranscomEventsJoinTableSql(
        conflationMapVersion,
        /* clearExisting = */ false
      );

      const tag = `Update conflation_map/transcom_events join table for ${conflationMapVersion}`;
      console.time(tag);
      await client.query(`
        BEGIN;

        ${sql};

        COMMIT; `);

      console.timeEnd(tag);
    })
  );

(async () => {
  const client = new Client();
  await client.connect();

  try {
    const conflationMapVersions = await listLoadedConflationMapVersions(client);

    if (Array.isArray(conflationMapVersions) && conflationMapVersions.length) {
      await updateJoinTables(client, conflationMapVersions);
    }
  } catch (err) {
    console.error(err);
  } finally {
    client.end();
  }
})();
