CREATE TABLE year_to_year_analysis___STATE__
  AS
    WITH cte_2022 AS (
      SELECT
          travel_time_code,
          segment_length,
          rank() OVER (ORDER BY segment_length DESC) AS segment_length_rank,
          dir_aadt,
          rank() OVER (ORDER BY dir_aadt DESC) AS dir_aadt_rank,
          occ_fac,
          rank() OVER (ORDER BY occ_fac desc) AS occ_fac_rank,
          lottr_amp,
          rank() OVER (ORDER BY lottr_amp DESC) AS lottr_amp_rank,
          tt_amp50pct,
          rank() OVER (ORDER BY tt_amp50pct DESC) AS tt_amp50pct_rank,
          tt_amp80pct,
          rank() OVER (ORDER BY tt_amp80pct DESC) AS tt_amp80pct_rank,
          lottr_midd,
          rank() OVER (ORDER BY lottr_midd DESC) AS lottr_midd_rank,
          tt_midd50pct,
          rank() OVER (ORDER BY tt_midd50pct DESC) AS tt_midd50pct_rank,
          tt_midd80pct,
          rank() OVER (ORDER BY tt_midd80pct DESC) AS tt_midd80pct_rank,
          lottr_pmp,
          rank() OVER (ORDER BY lottr_pmp DESC) AS lottr_pmp_rank,
          tt_pmp50pct,
          rank() OVER (ORDER BY tt_pmp50pct DESC) AS tt_pmp50pct_rank,
          tt_pmp80pct,
          rank() OVER (ORDER BY tt_pmp80pct DESC) AS tt_pmp80pct_rank,
          lottr_we,
          rank() OVER (ORDER BY lottr_we DESC) AS lottr_we_rank,
          tt_we50pct,
          rank() OVER (ORDER BY tt_we50pct DESC) AS tt_we50pct_rank,
          tt_we80pct,
          rank() OVER (ORDER BY tt_we80pct DESC) AS tt_we80pct_rank,
          tttr_amp,
          rank() OVER (ORDER BY tttr_amp DESC) AS tttr_amp_rank,
          ttt_amp50pct,
          rank() OVER (ORDER BY ttt_amp50pct DESC) AS ttt_amp50pct_rank,
          ttt_amp95pct,
          rank() OVER (ORDER BY ttt_amp95pct DESC) AS ttt_amp95pct_rank,
          tttr_midd,
          rank() OVER (ORDER BY tttr_midd DESC) AS tttr_midd_rank,
          ttt_midd50pct,
          rank() OVER (ORDER BY ttt_midd50pct DESC) AS ttt_midd50pct_rank,
          ttt_midd95pct,
          rank() OVER (ORDER BY ttt_midd95pct DESC) AS ttt_midd95pct_rank,
          tttr_pmp,
          rank() OVER (ORDER BY tttr_pmp DESC) AS tttr_pmp_rank,
          ttt_pmp50pct,
          rank() OVER (ORDER BY ttt_pmp50pct DESC) AS ttt_pmp50pct_rank,
          ttt_pmp95pct,
          rank() OVER (ORDER BY ttt_pmp95pct DESC) AS ttt_pmp95pct_rank,
          tttr_we,
          rank() OVER (ORDER BY tttr_we DESC) AS tttr_we_rank,
          ttt_we50pct,
          rank() OVER (ORDER BY ttt_we50pct DESC) AS ttt_we50pct_rank,
          ttt_we95pct,
          rank() OVER (ORDER BY ttt_we95pct DESC) AS ttt_we95pct_rank,
          tttr_ovn,
          rank() OVER (ORDER BY tttr_ovn DESC) AS tttr_ovn_rank,
          ttt_ovn50pct,
          rank() OVER (ORDER BY ttt_ovn50pct DESC) AS ttt_ovn50pct_rank,
          ttt_ovn95pct,
          rank() OVER (ORDER BY ttt_ovn95pct DESC) AS ttt_ovn95pct_rank,
          phed,
          rank() OVER (ORDER BY phed DESC) AS phed_rank
        FROM pm3___STATE___2022
    ), cte_2023 AS (
      SELECT
          travel_time_code,
          segment_length,
          rank() OVER (ORDER BY segment_length DESC) AS segment_length_rank,
          dir_aadt,
          rank() OVER (ORDER BY dir_aadt DESC) AS dir_aadt_rank,
          occ_fac,
          rank() OVER (ORDER BY occ_fac desc) AS occ_fac_rank,
          lottr_amp,
          rank() OVER (ORDER BY lottr_amp DESC) AS lottr_amp_rank,
          tt_amp50pct,
          rank() OVER (ORDER BY tt_amp50pct DESC) AS tt_amp50pct_rank,
          tt_amp80pct,
          rank() OVER (ORDER BY tt_amp80pct DESC) AS tt_amp80pct_rank,
          lottr_midd,
          rank() OVER (ORDER BY lottr_midd DESC) AS lottr_midd_rank,
          tt_midd50pct,
          rank() OVER (ORDER BY tt_midd50pct DESC) AS tt_midd50pct_rank,
          tt_midd80pct,
          rank() OVER (ORDER BY tt_midd80pct DESC) AS tt_midd80pct_rank,
          lottr_pmp,
          rank() OVER (ORDER BY lottr_pmp DESC) AS lottr_pmp_rank,
          tt_pmp50pct,
          rank() OVER (ORDER BY tt_pmp50pct DESC) AS tt_pmp50pct_rank,
          tt_pmp80pct,
          rank() OVER (ORDER BY tt_pmp80pct DESC) AS tt_pmp80pct_rank,
          lottr_we,
          rank() OVER (ORDER BY lottr_we DESC) AS lottr_we_rank,
          tt_we50pct,
          rank() OVER (ORDER BY tt_we50pct DESC) AS tt_we50pct_rank,
          tt_we80pct,
          rank() OVER (ORDER BY tt_we80pct DESC) AS tt_we80pct_rank,
          tttr_amp,
          rank() OVER (ORDER BY tttr_amp DESC) AS tttr_amp_rank,
          ttt_amp50pct,
          rank() OVER (ORDER BY ttt_amp50pct DESC) AS ttt_amp50pct_rank,
          ttt_amp95pct,
          rank() OVER (ORDER BY ttt_amp95pct DESC) AS ttt_amp95pct_rank,
          tttr_midd,
          rank() OVER (ORDER BY tttr_midd DESC) AS tttr_midd_rank,
          ttt_midd50pct,
          rank() OVER (ORDER BY ttt_midd50pct DESC) AS ttt_midd50pct_rank,
          ttt_midd95pct,
          rank() OVER (ORDER BY ttt_midd95pct DESC) AS ttt_midd95pct_rank,
          tttr_pmp,
          rank() OVER (ORDER BY tttr_pmp DESC) AS tttr_pmp_rank,
          ttt_pmp50pct,
          rank() OVER (ORDER BY ttt_pmp50pct DESC) AS ttt_pmp50pct_rank,
          ttt_pmp95pct,
          rank() OVER (ORDER BY ttt_pmp95pct DESC) AS ttt_pmp95pct_rank,
          tttr_we,
          rank() OVER (ORDER BY tttr_we DESC) AS tttr_we_rank,
          ttt_we50pct,
          rank() OVER (ORDER BY ttt_we50pct DESC) AS ttt_we50pct_rank,
          ttt_we95pct,
          rank() OVER (ORDER BY ttt_we95pct DESC) AS ttt_we95pct_rank,
          tttr_ovn,
          rank() OVER (ORDER BY tttr_ovn DESC) AS tttr_ovn_rank,
          ttt_ovn50pct,
          rank() OVER (ORDER BY ttt_ovn50pct DESC) AS ttt_ovn50pct_rank,
          ttt_ovn95pct,
          rank() OVER (ORDER BY ttt_ovn95pct DESC) AS ttt_ovn95pct_rank,
          phed,
          rank() OVER (ORDER BY phed DESC) AS phed_rank
        FROM pm3___STATE___2023
    )
      SELECT 
          travel_time_code,
          a.segment_length AS segment_length_2022,
          b.segment_length AS segment_length_2023,
          ROUND( CAST((b.segment_length - a.segment_length) AS FLOAT) / a.segment_length, 5) AS segment_length_diff_ratio,
          a.segment_length_rank AS segment_length_rank_2022,
          b.segment_length_rank AS segment_length_rank_2023,
          (b.segment_length_rank - a.segment_length_rank) AS segment_length_rank_diff,
          a.dir_aadt AS dir_aadt_2022,
          b.dir_aadt AS dir_aadt_2023,
          (b.dir_aadt - a.dir_aadt) AS dir_aadt_diff,
          ROUND( CAST((b.dir_aadt - a.dir_aadt) AS FLOAT) / a.dir_aadt, 5) AS dir_aadt_diff_ratio,
          a.dir_aadt_rank AS dir_aadt_rank_2022,
          b.dir_aadt_rank AS dir_aadt_rank_2023,
          (b.dir_aadt_rank - a.dir_aadt_rank) AS dir_aadt_rank_diff,
          a.occ_fac AS occ_fac_2022,
          b.occ_fac AS occ_fac_2023,
          ROUND( CAST((b.occ_fac - a.occ_fac) AS FLOAT) / a.occ_fac, 5) AS occ_fac_diff_ratio,
          a.occ_fac_rank AS occ_fac_rank_2022,
          b.occ_fac_rank AS occ_fac_rank_2023,
          (b.occ_fac_rank - a.occ_fac_rank) AS occ_fac_rank_diff,
          a.lottr_amp AS lottr_amp_2022,
          b.lottr_amp AS lottr_amp_2023,
          ROUND( CAST((b.lottr_amp - a.lottr_amp) AS FLOAT) / a.lottr_amp, 5) AS lottr_amp_diff_ratio,
          a.lottr_amp_rank AS lottr_amp_rank_2022,
          b.lottr_amp_rank AS lottr_amp_rank_2023,
          (b.lottr_amp_rank - a.lottr_amp_rank) AS lottr_amp_rank_diff,
          a.tt_amp50pct AS tt_amp50pct_2022,
          b.tt_amp50pct AS tt_amp50pct_2023,
          ROUND( CAST((b.tt_amp50pct - a.tt_amp50pct) AS FLOAT) / a.tt_amp50pct, 5) AS tt_amp50pct_diff_ratio,
          a.tt_amp50pct_rank AS tt_amp50pct_rank_2022,
          b.tt_amp50pct_rank AS tt_amp50pct_rank_2023,
          (b.tt_amp50pct_rank - a.tt_amp50pct_rank) AS tt_amp50pct_rank_diff,
          a.tt_amp80pct AS tt_amp80pct_2022,
          b.tt_amp80pct AS tt_amp80pct_2023,
          ROUND( CAST((b.tt_amp80pct - a.tt_amp80pct) AS FLOAT) / a.tt_amp80pct, 5) AS tt_amp80pct_diff_ratio,
          a.tt_amp80pct_rank AS tt_amp80pct_rank_2022,
          b.tt_amp80pct_rank AS tt_amp80pct_rank_2023,
          (b.tt_amp80pct_rank - a.tt_amp80pct_rank) AS tt_amp80pct_rank_diff,
          a.lottr_midd AS lottr_midd_2022,
          b.lottr_midd AS lottr_midd_2023,
          ROUND( CAST((b.lottr_midd - a.lottr_midd) AS FLOAT) / a.lottr_midd, 5) AS lottr_midd_diff_ratio,
          a.lottr_midd_rank AS lottr_midd_rank_2022,
          b.lottr_midd_rank AS lottr_midd_rank_2023,
          (b.lottr_midd_rank - a.lottr_midd_rank) AS lottr_midd_rank_diff,
          a.tt_midd50pct AS tt_midd50pct_2022,
          b.tt_midd50pct AS tt_midd50pct_2023,
          ROUND( CAST((b.tt_midd50pct - a.tt_midd50pct) AS FLOAT) / a.tt_midd50pct, 5) AS tt_midd50pct_diff_ratio,
          a.tt_midd50pct_rank AS tt_midd50pct_rank_2022,
          b.tt_midd50pct_rank AS tt_midd50pct_rank_2023,
          (b.tt_midd50pct_rank - a.tt_midd50pct_rank) AS tt_midd50pct_rank_diff,
          a.tt_midd80pct AS tt_midd80pct_2022,
          b.tt_midd80pct AS tt_midd80pct_2023,
          ROUND( CAST((b.tt_midd80pct - a.tt_midd80pct) AS FLOAT) / a.tt_midd80pct, 5) AS tt_midd80pct_diff_ratio,
          a.tt_midd80pct_rank AS tt_midd80pct_rank_2022,
          b.tt_midd80pct_rank AS tt_midd80pct_rank_2023,
          (b.tt_midd80pct_rank - a.tt_midd80pct_rank) AS tt_midd80pct_rank_diff,
          a.lottr_pmp AS lottr_pmp_2022,
          b.lottr_pmp AS lottr_pmp_2023,
          ROUND( CAST((b.lottr_pmp - a.lottr_pmp) AS FLOAT) / a.lottr_pmp, 5) AS lottr_pmp_diff_ratio,
          a.lottr_pmp_rank AS lottr_pmp_rank_2022,
          b.lottr_pmp_rank AS lottr_pmp_rank_2023,
          (b.lottr_pmp_rank - a.lottr_pmp_rank) AS lottr_pmp_rank_diff,
          a.tt_pmp50pct AS tt_pmp50pct_2022,
          b.tt_pmp50pct AS tt_pmp50pct_2023,
          ROUND( CAST((b.tt_pmp50pct - a.tt_pmp50pct) AS FLOAT) / a.tt_pmp50pct, 5) AS tt_pmp50pct_diff_ratio,
          a.tt_pmp50pct_rank AS tt_pmp50pct_rank_2022,
          b.tt_pmp50pct_rank AS tt_pmp50pct_rank_2023,
          (b.tt_pmp50pct_rank - a.tt_pmp50pct_rank) AS tt_pmp50pct_rank_diff,
          a.tt_pmp80pct AS tt_pmp80pct_2022,
          b.tt_pmp80pct AS tt_pmp80pct_2023,
          ROUND( CAST((b.tt_pmp80pct - a.tt_pmp80pct) AS FLOAT) / a.tt_pmp80pct, 5) AS tt_pmp80pct_diff_ratio,
          a.tt_pmp80pct_rank AS tt_pmp80pct_rank_2022,
          b.tt_pmp80pct_rank AS tt_pmp80pct_rank_2023,
          (b.tt_pmp80pct_rank - a.tt_pmp80pct_rank) AS tt_pmp80pct_rank_diff,
          a.lottr_we AS lottr_we_2022,
          b.lottr_we AS lottr_we_2023,
          ROUND( CAST((b.lottr_we - a.lottr_we) AS FLOAT) / a.lottr_we, 5) AS lottr_we_diff_ratio,
          a.lottr_we_rank AS lottr_we_rank_2022,
          b.lottr_we_rank AS lottr_we_rank_2023,
          (b.lottr_we_rank - a.lottr_we_rank) AS lottr_we_rank_diff,
          a.tt_we50pct AS tt_we50pct_2022,
          b.tt_we50pct AS tt_we50pct_2023,
          ROUND( CAST((b.tt_we50pct - a.tt_we50pct) AS FLOAT) / a.tt_we50pct, 5) AS tt_we50pct_diff_ratio,
          a.tt_we50pct_rank AS tt_we50pct_rank_2022,
          b.tt_we50pct_rank AS tt_we50pct_rank_2023,
          (b.tt_we50pct_rank - a.tt_we50pct_rank) AS tt_we50pct_rank_diff,
          a.tt_we80pct AS tt_we80pct_2022,
          b.tt_we80pct AS tt_we80pct_2023,
          ROUND( CAST((b.tt_we80pct - a.tt_we80pct) AS FLOAT) / a.tt_we80pct, 5) AS tt_we80pct_diff_ratio,
          a.tt_we80pct_rank AS tt_we80pct_rank_2022,
          b.tt_we80pct_rank AS tt_we80pct_rank_2023,
          (b.tt_we80pct_rank - a.tt_we80pct_rank) AS tt_we80pct_rank_diff,
          a.tttr_amp AS tttr_amp_2022,
          b.tttr_amp AS tttr_amp_2023,
          ROUND( CAST((b.tttr_amp - a.tttr_amp) AS FLOAT) / a.tttr_amp, 5) AS tttr_amp_diff_ratio,
          a.tttr_amp_rank AS tttr_amp_rank_2022,
          b.tttr_amp_rank AS tttr_amp_rank_2023,
          (b.tttr_amp_rank - a.tttr_amp_rank) AS tttr_amp_rank_diff,
          a.ttt_amp50pct AS ttt_amp50pct_2022,
          b.ttt_amp50pct AS ttt_amp50pct_2023,
          ROUND( CAST((b.ttt_amp50pct - a.ttt_amp50pct) AS FLOAT) / a.ttt_amp50pct, 5) AS ttt_amp50pct_diff_ratio,
          a.ttt_amp50pct_rank AS ttt_amp50pct_rank_2022,
          b.ttt_amp50pct_rank AS ttt_amp50pct_rank_2023,
          (b.ttt_amp50pct_rank - a.ttt_amp50pct_rank) AS ttt_amp50pct_rank_diff,
          a.ttt_amp95pct AS ttt_amp95pct_2022,
          b.ttt_amp95pct AS ttt_amp95pct_2023,
          ROUND( CAST((b.ttt_amp95pct - a.ttt_amp95pct) AS FLOAT) / a.ttt_amp95pct, 5) AS ttt_amp95pct_diff_ratio,
          a.ttt_amp95pct_rank AS ttt_amp95pct_rank_2022,
          b.ttt_amp95pct_rank AS ttt_amp95pct_rank_2023,
          (b.ttt_amp95pct_rank - a.ttt_amp95pct_rank) AS ttt_amp95pct_rank_diff,
          a.tttr_midd AS tttr_midd_2022,
          b.tttr_midd AS tttr_midd_2023,
          ROUND( CAST((b.tttr_midd - a.tttr_midd) AS FLOAT) / a.tttr_midd, 5) AS tttr_midd_diff_ratio,
          a.tttr_midd_rank AS tttr_midd_rank_2022,
          b.tttr_midd_rank AS tttr_midd_rank_2023,
          (b.tttr_midd_rank - a.tttr_midd_rank) AS tttr_midd_rank_diff,
          a.ttt_midd50pct AS ttt_midd50pct_2022,
          b.ttt_midd50pct AS ttt_midd50pct_2023,
          ROUND( CAST((b.ttt_midd50pct - a.ttt_midd50pct) AS FLOAT) / a.ttt_midd50pct, 5) AS ttt_midd50pct_diff_ratio,
          a.ttt_midd50pct_rank AS ttt_midd50pct_rank_2022,
          b.ttt_midd50pct_rank AS ttt_midd50pct_rank_2023,
          (b.ttt_midd50pct_rank - a.ttt_midd50pct_rank) AS ttt_midd50pct_rank_diff,
          a.ttt_midd95pct AS ttt_midd95pct_2022,
          b.ttt_midd95pct AS ttt_midd95pct_2023,
          ROUND( CAST((b.ttt_midd95pct - a.ttt_midd95pct) AS FLOAT) / a.ttt_midd95pct, 5) AS ttt_midd95pct_diff_ratio,
          a.ttt_midd95pct_rank AS ttt_midd95pct_rank_2022,
          b.ttt_midd95pct_rank AS ttt_midd95pct_rank_2023,
          (b.ttt_midd95pct_rank - a.ttt_midd95pct_rank) AS ttt_midd95pct_rank_diff,
          a.tttr_pmp AS tttr_pmp_2022,
          b.tttr_pmp AS tttr_pmp_2023,
          ROUND( CAST((b.tttr_pmp - a.tttr_pmp) AS FLOAT) / a.tttr_pmp, 5) AS tttr_pmp_diff_ratio,
          a.tttr_pmp_rank AS tttr_pmp_rank_2022,
          b.tttr_pmp_rank AS tttr_pmp_rank_2023,
          (b.tttr_pmp_rank - a.tttr_pmp_rank) AS tttr_pmp_rank_diff,
          a.ttt_pmp50pct AS ttt_pmp50pct_2022,
          b.ttt_pmp50pct AS ttt_pmp50pct_2023,
          ROUND( CAST((b.ttt_pmp50pct - a.ttt_pmp50pct) AS FLOAT) / a.ttt_pmp50pct, 5) AS ttt_pmp50pct_diff_ratio,
          a.ttt_pmp50pct_rank AS ttt_pmp50pct_rank_2022,
          b.ttt_pmp50pct_rank AS ttt_pmp50pct_rank_2023,
          (b.ttt_pmp50pct_rank - a.ttt_pmp50pct_rank) AS ttt_pmp50pct_rank_diff,
          a.ttt_pmp95pct AS ttt_pmp95pct_2022,
          b.ttt_pmp95pct AS ttt_pmp95pct_2023,
          ROUND( CAST((b.ttt_pmp95pct - a.ttt_pmp95pct) AS FLOAT) / a.ttt_pmp95pct, 5) AS ttt_pmp95pct_diff_ratio,
          a.ttt_pmp95pct_rank AS ttt_pmp95pct_rank_2022,
          b.ttt_pmp95pct_rank AS ttt_pmp95pct_rank_2023,
          (b.ttt_pmp95pct_rank - a.ttt_pmp95pct_rank) AS ttt_pmp95pct_rank_diff,
          a.tttr_we AS tttr_we_2022,
          b.tttr_we AS tttr_we_2023,
          ROUND( CAST((b.tttr_we - a.tttr_we) AS FLOAT) / a.tttr_we, 5) AS tttr_we_diff_ratio,
          a.tttr_we_rank AS tttr_we_rank_2022,
          b.tttr_we_rank AS tttr_we_rank_2023,
          (b.tttr_we_rank - a.tttr_we_rank) AS tttr_we_rank_diff,
          a.ttt_we50pct AS ttt_we50pct_2022,
          b.ttt_we50pct AS ttt_we50pct_2023,
          ROUND( CAST((b.ttt_we50pct - a.ttt_we50pct) AS FLOAT) / a.ttt_we50pct, 5) AS ttt_we50pct_diff_ratio,
          a.ttt_we50pct_rank AS ttt_we50pct_rank_2022,
          b.ttt_we50pct_rank AS ttt_we50pct_rank_2023,
          (b.ttt_we50pct_rank - a.ttt_we50pct_rank) AS ttt_we50pct_rank_diff,
          a.ttt_we95pct AS ttt_we95pct_2022,
          b.ttt_we95pct AS ttt_we95pct_2023,
          ROUND( CAST((b.ttt_we95pct - a.ttt_we95pct) AS FLOAT) / a.ttt_we95pct, 5) AS ttt_we95pct_diff_ratio,
          a.ttt_we95pct_rank AS ttt_we95pct_rank_2022,
          b.ttt_we95pct_rank AS ttt_we95pct_rank_2023,
          (b.ttt_we95pct_rank - a.ttt_we95pct_rank) AS ttt_we95pct_rank_diff,
          a.tttr_ovn AS tttr_ovn_2022,
          b.tttr_ovn AS tttr_ovn_2023,
          ROUND( CAST((b.tttr_ovn - a.tttr_ovn) AS FLOAT) / a.tttr_ovn, 5) AS tttr_ovn_diff_ratio,
          a.tttr_ovn_rank AS tttr_ovn_rank_2022,
          b.tttr_ovn_rank AS tttr_ovn_rank_2023,
          (b.tttr_ovn_rank - a.tttr_ovn_rank) AS tttr_ovn_rank_diff,
          a.ttt_ovn50pct AS ttt_ovn50pct_2022,
          b.ttt_ovn50pct AS ttt_ovn50pct_2023,
          ROUND( CAST((b.ttt_ovn50pct - a.ttt_ovn50pct) AS FLOAT) / a.ttt_ovn50pct, 5) AS ttt_ovn50pct_diff_ratio,
          a.ttt_ovn50pct_rank AS ttt_ovn50pct_rank_2022,
          b.ttt_ovn50pct_rank AS ttt_ovn50pct_rank_2023,
          (b.ttt_ovn50pct_rank - a.ttt_ovn50pct_rank) AS ttt_ovn50pct_rank_diff,
          a.ttt_ovn95pct AS ttt_ovn95pct_2022,
          b.ttt_ovn95pct AS ttt_ovn95pct_2023,
          ROUND( CAST((b.ttt_ovn95pct - a.ttt_ovn95pct) AS FLOAT) / a.ttt_ovn95pct, 5) AS ttt_ovn95pct_diff_ratio,
          a.ttt_ovn95pct_rank AS ttt_ovn95pct_rank_2022,
          b.ttt_ovn95pct_rank AS ttt_ovn95pct_rank_2023,
          (b.ttt_ovn95pct_rank - a.ttt_ovn95pct_rank) AS ttt_ovn95pct_rank_diff,
          a.phed AS phed_2022,
          b.phed AS phed_2023,
          ROUND( CAST((b.phed - a.phed) AS FLOAT) / a.phed, 5) AS phed_diff_ratio,
          a.phed_rank AS phed_rank_2022,
          b.phed_rank AS phed_rank_2023,
          (b.phed_rank - a.phed_rank) AS phed_rank_diff
      FROM cte_2022 AS a
        LEFT JOIN cte_2023 AS b USING(travel_time_code)
      UNION ALL
      SELECT 
          travel_time_code,
          a.segment_length AS segment_length_2022,
          b.segment_length AS segment_length_2023,
          ROUND( CAST((b.segment_length - a.segment_length) AS FLOAT) / a.segment_length, 5) AS segment_length_diff_ratio,
          a.segment_length_rank AS segment_length_rank_2022,
          b.segment_length_rank AS segment_length_rank_2023,
          (b.segment_length_rank - a.segment_length_rank) AS segment_length_rank_diff,
          a.dir_aadt AS dir_aadt_2022,
          b.dir_aadt AS dir_aadt_2023,
          (b.dir_aadt - a.dir_aadt) AS dir_aadt_diff,
          ROUND( CAST((b.dir_aadt - a.dir_aadt) AS FLOAT) / a.dir_aadt, 5) AS dir_aadt_diff_ratio,
          a.dir_aadt_rank AS dir_aadt_rank_2022,
          b.dir_aadt_rank AS dir_aadt_rank_2023,
          (b.dir_aadt_rank - a.dir_aadt_rank) AS dir_aadt_rank_diff,
          a.occ_fac AS occ_fac_2022,
          b.occ_fac AS occ_fac_2023,
          ROUND( CAST((b.occ_fac - a.occ_fac) AS FLOAT) / a.occ_fac, 5) AS occ_fac_diff_ratio,
          a.occ_fac_rank AS occ_fac_rank_2022,
          b.occ_fac_rank AS occ_fac_rank_2023,
          (b.occ_fac_rank - a.occ_fac_rank) AS occ_fac_rank_diff,
          a.lottr_amp AS lottr_amp_2022,
          b.lottr_amp AS lottr_amp_2023,
          ROUND( CAST((b.lottr_amp - a.lottr_amp) AS FLOAT) / a.lottr_amp, 5) AS lottr_amp_diff_ratio,
          a.lottr_amp_rank AS lottr_amp_rank_2022,
          b.lottr_amp_rank AS lottr_amp_rank_2023,
          (b.lottr_amp_rank - a.lottr_amp_rank) AS lottr_amp_rank_diff,
          a.tt_amp50pct AS tt_amp50pct_2022,
          b.tt_amp50pct AS tt_amp50pct_2023,
          ROUND( CAST((b.tt_amp50pct - a.tt_amp50pct) AS FLOAT) / a.tt_amp50pct, 5) AS tt_amp50pct_diff_ratio,
          a.tt_amp50pct_rank AS tt_amp50pct_rank_2022,
          b.tt_amp50pct_rank AS tt_amp50pct_rank_2023,
          (b.tt_amp50pct_rank - a.tt_amp50pct_rank) AS tt_amp50pct_rank_diff,
          a.tt_amp80pct AS tt_amp80pct_2022,
          b.tt_amp80pct AS tt_amp80pct_2023,
          ROUND( CAST((b.tt_amp80pct - a.tt_amp80pct) AS FLOAT) / a.tt_amp80pct, 5) AS tt_amp80pct_diff_ratio,
          a.tt_amp80pct_rank AS tt_amp80pct_rank_2022,
          b.tt_amp80pct_rank AS tt_amp80pct_rank_2023,
          (b.tt_amp80pct_rank - a.tt_amp80pct_rank) AS tt_amp80pct_rank_diff,
          a.lottr_midd AS lottr_midd_2022,
          b.lottr_midd AS lottr_midd_2023,
          ROUND( CAST((b.lottr_midd - a.lottr_midd) AS FLOAT) / a.lottr_midd, 5) AS lottr_midd_diff_ratio,
          a.lottr_midd_rank AS lottr_midd_rank_2022,
          b.lottr_midd_rank AS lottr_midd_rank_2023,
          (b.lottr_midd_rank - a.lottr_midd_rank) AS lottr_midd_rank_diff,
          a.tt_midd50pct AS tt_midd50pct_2022,
          b.tt_midd50pct AS tt_midd50pct_2023,
          ROUND( CAST((b.tt_midd50pct - a.tt_midd50pct) AS FLOAT) / a.tt_midd50pct, 5) AS tt_midd50pct_diff_ratio,
          a.tt_midd50pct_rank AS tt_midd50pct_rank_2022,
          b.tt_midd50pct_rank AS tt_midd50pct_rank_2023,
          (b.tt_midd50pct_rank - a.tt_midd50pct_rank) AS tt_midd50pct_rank_diff,
          a.tt_midd80pct AS tt_midd80pct_2022,
          b.tt_midd80pct AS tt_midd80pct_2023,
          ROUND( CAST((b.tt_midd80pct - a.tt_midd80pct) AS FLOAT) / a.tt_midd80pct, 5) AS tt_midd80pct_diff_ratio,
          a.tt_midd80pct_rank AS tt_midd80pct_rank_2022,
          b.tt_midd80pct_rank AS tt_midd80pct_rank_2023,
          (b.tt_midd80pct_rank - a.tt_midd80pct_rank) AS tt_midd80pct_rank_diff,
          a.lottr_pmp AS lottr_pmp_2022,
          b.lottr_pmp AS lottr_pmp_2023,
          ROUND( CAST((b.lottr_pmp - a.lottr_pmp) AS FLOAT) / a.lottr_pmp, 5) AS lottr_pmp_diff_ratio,
          a.lottr_pmp_rank AS lottr_pmp_rank_2022,
          b.lottr_pmp_rank AS lottr_pmp_rank_2023,
          (b.lottr_pmp_rank - a.lottr_pmp_rank) AS lottr_pmp_rank_diff,
          a.tt_pmp50pct AS tt_pmp50pct_2022,
          b.tt_pmp50pct AS tt_pmp50pct_2023,
          ROUND( CAST((b.tt_pmp50pct - a.tt_pmp50pct) AS FLOAT) / a.tt_pmp50pct, 5) AS tt_pmp50pct_diff_ratio,
          a.tt_pmp50pct_rank AS tt_pmp50pct_rank_2022,
          b.tt_pmp50pct_rank AS tt_pmp50pct_rank_2023,
          (b.tt_pmp50pct_rank - a.tt_pmp50pct_rank) AS tt_pmp50pct_rank_diff,
          a.tt_pmp80pct AS tt_pmp80pct_2022,
          b.tt_pmp80pct AS tt_pmp80pct_2023,
          ROUND( CAST((b.tt_pmp80pct - a.tt_pmp80pct) AS FLOAT) / a.tt_pmp80pct, 5) AS tt_pmp80pct_diff_ratio,
          a.tt_pmp80pct_rank AS tt_pmp80pct_rank_2022,
          b.tt_pmp80pct_rank AS tt_pmp80pct_rank_2023,
          (b.tt_pmp80pct_rank - a.tt_pmp80pct_rank) AS tt_pmp80pct_rank_diff,
          a.lottr_we AS lottr_we_2022,
          b.lottr_we AS lottr_we_2023,
          ROUND( CAST((b.lottr_we - a.lottr_we) AS FLOAT) / a.lottr_we, 5) AS lottr_we_diff_ratio,
          a.lottr_we_rank AS lottr_we_rank_2022,
          b.lottr_we_rank AS lottr_we_rank_2023,
          (b.lottr_we_rank - a.lottr_we_rank) AS lottr_we_rank_diff,
          a.tt_we50pct AS tt_we50pct_2022,
          b.tt_we50pct AS tt_we50pct_2023,
          ROUND( CAST((b.tt_we50pct - a.tt_we50pct) AS FLOAT) / a.tt_we50pct, 5) AS tt_we50pct_diff_ratio,
          a.tt_we50pct_rank AS tt_we50pct_rank_2022,
          b.tt_we50pct_rank AS tt_we50pct_rank_2023,
          (b.tt_we50pct_rank - a.tt_we50pct_rank) AS tt_we50pct_rank_diff,
          a.tt_we80pct AS tt_we80pct_2022,
          b.tt_we80pct AS tt_we80pct_2023,
          ROUND( CAST((b.tt_we80pct - a.tt_we80pct) AS FLOAT) / a.tt_we80pct, 5) AS tt_we80pct_diff_ratio,
          a.tt_we80pct_rank AS tt_we80pct_rank_2022,
          b.tt_we80pct_rank AS tt_we80pct_rank_2023,
          (b.tt_we80pct_rank - a.tt_we80pct_rank) AS tt_we80pct_rank_diff,
          a.tttr_amp AS tttr_amp_2022,
          b.tttr_amp AS tttr_amp_2023,
          ROUND( CAST((b.tttr_amp - a.tttr_amp) AS FLOAT) / a.tttr_amp, 5) AS tttr_amp_diff_ratio,
          a.tttr_amp_rank AS tttr_amp_rank_2022,
          b.tttr_amp_rank AS tttr_amp_rank_2023,
          (b.tttr_amp_rank - a.tttr_amp_rank) AS tttr_amp_rank_diff,
          a.ttt_amp50pct AS ttt_amp50pct_2022,
          b.ttt_amp50pct AS ttt_amp50pct_2023,
          ROUND( CAST((b.ttt_amp50pct - a.ttt_amp50pct) AS FLOAT) / a.ttt_amp50pct, 5) AS ttt_amp50pct_diff_ratio,
          a.ttt_amp50pct_rank AS ttt_amp50pct_rank_2022,
          b.ttt_amp50pct_rank AS ttt_amp50pct_rank_2023,
          (b.ttt_amp50pct_rank - a.ttt_amp50pct_rank) AS ttt_amp50pct_rank_diff,
          a.ttt_amp95pct AS ttt_amp95pct_2022,
          b.ttt_amp95pct AS ttt_amp95pct_2023,
          ROUND( CAST((b.ttt_amp95pct - a.ttt_amp95pct) AS FLOAT) / a.ttt_amp95pct, 5) AS ttt_amp95pct_diff_ratio,
          a.ttt_amp95pct_rank AS ttt_amp95pct_rank_2022,
          b.ttt_amp95pct_rank AS ttt_amp95pct_rank_2023,
          (b.ttt_amp95pct_rank - a.ttt_amp95pct_rank) AS ttt_amp95pct_rank_diff,
          a.tttr_midd AS tttr_midd_2022,
          b.tttr_midd AS tttr_midd_2023,
          ROUND( CAST((b.tttr_midd - a.tttr_midd) AS FLOAT) / a.tttr_midd, 5) AS tttr_midd_diff_ratio,
          a.tttr_midd_rank AS tttr_midd_rank_2022,
          b.tttr_midd_rank AS tttr_midd_rank_2023,
          (b.tttr_midd_rank - a.tttr_midd_rank) AS tttr_midd_rank_diff,
          a.ttt_midd50pct AS ttt_midd50pct_2022,
          b.ttt_midd50pct AS ttt_midd50pct_2023,
          ROUND( CAST((b.ttt_midd50pct - a.ttt_midd50pct) AS FLOAT) / a.ttt_midd50pct, 5) AS ttt_midd50pct_diff_ratio,
          a.ttt_midd50pct_rank AS ttt_midd50pct_rank_2022,
          b.ttt_midd50pct_rank AS ttt_midd50pct_rank_2023,
          (b.ttt_midd50pct_rank - a.ttt_midd50pct_rank) AS ttt_midd50pct_rank_diff,
          a.ttt_midd95pct AS ttt_midd95pct_2022,
          b.ttt_midd95pct AS ttt_midd95pct_2023,
          ROUND( CAST((b.ttt_midd95pct - a.ttt_midd95pct) AS FLOAT) / a.ttt_midd95pct, 5) AS ttt_midd95pct_diff_ratio,
          a.ttt_midd95pct_rank AS ttt_midd95pct_rank_2022,
          b.ttt_midd95pct_rank AS ttt_midd95pct_rank_2023,
          (b.ttt_midd95pct_rank - a.ttt_midd95pct_rank) AS ttt_midd95pct_rank_diff,
          a.tttr_pmp AS tttr_pmp_2022,
          b.tttr_pmp AS tttr_pmp_2023,
          ROUND( CAST((b.tttr_pmp - a.tttr_pmp) AS FLOAT) / a.tttr_pmp, 5) AS tttr_pmp_diff_ratio,
          a.tttr_pmp_rank AS tttr_pmp_rank_2022,
          b.tttr_pmp_rank AS tttr_pmp_rank_2023,
          (b.tttr_pmp_rank - a.tttr_pmp_rank) AS tttr_pmp_rank_diff,
          a.ttt_pmp50pct AS ttt_pmp50pct_2022,
          b.ttt_pmp50pct AS ttt_pmp50pct_2023,
          ROUND( CAST((b.ttt_pmp50pct - a.ttt_pmp50pct) AS FLOAT) / a.ttt_pmp50pct, 5) AS ttt_pmp50pct_diff_ratio,
          a.ttt_pmp50pct_rank AS ttt_pmp50pct_rank_2022,
          b.ttt_pmp50pct_rank AS ttt_pmp50pct_rank_2023,
          (b.ttt_pmp50pct_rank - a.ttt_pmp50pct_rank) AS ttt_pmp50pct_rank_diff,
          a.ttt_pmp95pct AS ttt_pmp95pct_2022,
          b.ttt_pmp95pct AS ttt_pmp95pct_2023,
          ROUND( CAST((b.ttt_pmp95pct - a.ttt_pmp95pct) AS FLOAT) / a.ttt_pmp95pct, 5) AS ttt_pmp95pct_diff_ratio,
          a.ttt_pmp95pct_rank AS ttt_pmp95pct_rank_2022,
          b.ttt_pmp95pct_rank AS ttt_pmp95pct_rank_2023,
          (b.ttt_pmp95pct_rank - a.ttt_pmp95pct_rank) AS ttt_pmp95pct_rank_diff,
          a.tttr_we AS tttr_we_2022,
          b.tttr_we AS tttr_we_2023,
          ROUND( CAST((b.tttr_we - a.tttr_we) AS FLOAT) / a.tttr_we, 5) AS tttr_we_diff_ratio,
          a.tttr_we_rank AS tttr_we_rank_2022,
          b.tttr_we_rank AS tttr_we_rank_2023,
          (b.tttr_we_rank - a.tttr_we_rank) AS tttr_we_rank_diff,
          a.ttt_we50pct AS ttt_we50pct_2022,
          b.ttt_we50pct AS ttt_we50pct_2023,
          ROUND( CAST((b.ttt_we50pct - a.ttt_we50pct) AS FLOAT) / a.ttt_we50pct, 5) AS ttt_we50pct_diff_ratio,
          a.ttt_we50pct_rank AS ttt_we50pct_rank_2022,
          b.ttt_we50pct_rank AS ttt_we50pct_rank_2023,
          (b.ttt_we50pct_rank - a.ttt_we50pct_rank) AS ttt_we50pct_rank_diff,
          a.ttt_we95pct AS ttt_we95pct_2022,
          b.ttt_we95pct AS ttt_we95pct_2023,
          ROUND( CAST((b.ttt_we95pct - a.ttt_we95pct) AS FLOAT) / a.ttt_we95pct, 5) AS ttt_we95pct_diff_ratio,
          a.ttt_we95pct_rank AS ttt_we95pct_rank_2022,
          b.ttt_we95pct_rank AS ttt_we95pct_rank_2023,
          (b.ttt_we95pct_rank - a.ttt_we95pct_rank) AS ttt_we95pct_rank_diff,
          a.tttr_ovn AS tttr_ovn_2022,
          b.tttr_ovn AS tttr_ovn_2023,
          ROUND( CAST((b.tttr_ovn - a.tttr_ovn) AS FLOAT) / a.tttr_ovn, 5) AS tttr_ovn_diff_ratio,
          a.tttr_ovn_rank AS tttr_ovn_rank_2022,
          b.tttr_ovn_rank AS tttr_ovn_rank_2023,
          (b.tttr_ovn_rank - a.tttr_ovn_rank) AS tttr_ovn_rank_diff,
          a.ttt_ovn50pct AS ttt_ovn50pct_2022,
          b.ttt_ovn50pct AS ttt_ovn50pct_2023,
          ROUND( CAST((b.ttt_ovn50pct - a.ttt_ovn50pct) AS FLOAT) / a.ttt_ovn50pct, 5) AS ttt_ovn50pct_diff_ratio,
          a.ttt_ovn50pct_rank AS ttt_ovn50pct_rank_2022,
          b.ttt_ovn50pct_rank AS ttt_ovn50pct_rank_2023,
          (b.ttt_ovn50pct_rank - a.ttt_ovn50pct_rank) AS ttt_ovn50pct_rank_diff,
          a.ttt_ovn95pct AS ttt_ovn95pct_2022,
          b.ttt_ovn95pct AS ttt_ovn95pct_2023,
          ROUND( CAST((b.ttt_ovn95pct - a.ttt_ovn95pct) AS FLOAT) / a.ttt_ovn95pct, 5) AS ttt_ovn95pct_diff_ratio,
          a.ttt_ovn95pct_rank AS ttt_ovn95pct_rank_2022,
          b.ttt_ovn95pct_rank AS ttt_ovn95pct_rank_2023,
          (b.ttt_ovn95pct_rank - a.ttt_ovn95pct_rank) AS ttt_ovn95pct_rank_diff,
          a.phed AS phed_2022,
          b.phed AS phed_2023,
          ROUND( CAST((b.phed - a.phed) AS FLOAT) / a.phed, 5) AS phed_diff_ratio,
          a.phed_rank AS phed_rank_2022,
          b.phed_rank AS phed_rank_2023,
          (b.phed_rank - a.phed_rank) AS phed_rank_diff
      FROM cte_2023 AS b
        LEFT JOIN cte_2022 AS a USING(travel_time_code)
      WHERE a.travel_time_code IS NULL
;
