version: '2'
services:
    db:
      image: starefossen/pgrouting:10.1-2.4-2.5
      container_name: npmrds_api_db
      network_mode: "host"
      ports:
        - "5434:5432"
      volumes:
        - ./pg_data:/data
        - ./sqlScripts/:/sqlScripts/
      env_file: "../config/postgres.docker.env"
      environment:
        - PGDATA=/data
