BEGIN;

CREATE TABLE public.tmc_attributes (
   tmc                   CHARACTER VARYING,
   tmctype               CHARACTER VARYING,
   roadnumber            CHARACTER VARYING,
   roadname              CHARACTER VARYING,
   firstname             CHARACTER VARYING,
   tmclinear             BIGINT,
   country               CHARACTER VARYING,
   statename             CHARACTER VARYING,
   county                CHARACTER VARYING,
   zip                   CHARACTER VARYING,
   direction             CHARACTER VARYING,
   startlat              DOUBLE PRECISION,
   startlong             DOUBLE PRECISION,
   endlat                DOUBLE PRECISION,
   endlong               DOUBLE PRECISION,
   miles                 DOUBLE PRECISION,
   frc                   BIGINT,
   border_set            CHARACTER VARYING,
   f_system              BIGINT,
   urban_code            BIGINT,
   faciltype             BIGINT,
   structype             BIGINT,
   thrulanes             BIGINT,
   route_numb            BIGINT,
   route_sign            BIGINT,
   route_qual            BIGINT,
   altrtename            CHARACTER VARYING,
   aadt                  BIGINT,
   aadt_singl            BIGINT,
   aadt_combi            BIGINT,
   nhs                   BIGINT,
   nhs_pct               BIGINT,
   strhnt_typ            BIGINT,
   strhnt_pct            BIGINT,
   truck                 BIGINT,
   admin_level_1         CHARACTER VARYING,
   admin_level_2         CHARACTER VARYING,
   admin_level_3         CHARACTER VARYING,
   distance              DOUBLE PRECISION,
   length                DOUBLE PRECISION,
   road_number           CHARACTER VARYING,
   road_name             CHARACTER VARYING,
   latitude              DOUBLE PRECISION,
   longitude             DOUBLE PRECISION,
   road_direction        TEXT,
   occupancy_factor      REAL,
   state                 CHARACTER(2),
   state_code            CHAR(2), 
   county_code           CHAR(5),
   is_interstate         BOOLEAN,
   is_controlled_access  BOOLEAN,
   avg_speedlimit        REAL,
   avg_vehicle_occupancy REAL,
   mpo_code              CHARACTER VARYING,
   mpo_acrony            CHARACTER VARYING,
   mpo_name              CHARACTER VARYING,
   ua_code               CHARACTER VARYING,
   ua_name               CHARACTER VARYING,
   region_code           SMALLINT,
   region_name           CHARACTER VARYING,
   congestion_level      traffic_dist_congestion_level_type,
   directionality        traffic_dist_directionality_type,
   requires_offset       BOOLEAN,
   bounding_box          BOX2D
) WITH (fillfactor=100, autovacuum_enabled=false);

COMMIT;
