CREATE TABLE IF NOT EXISTS pm3_hpms (
year_record         INTEGER,
state_code          TEXT,
travel_time_code    TEXT PRIMARY KEY,
f_system            INTEGER,
urban_code          TEXT,
facility_type       INTEGER,
nhs                 INTEGER,
segment_length      REAL,
directionality      INTEGER,
dir_aadt            INTEGER,
occ_fac             REAL,
lottr_amp           REAL,
tt_amp50pct         INTEGER,
tt_amp80pct         INTEGER,
lottr_midd          INTEGER,
tt_midd50pct        INTEGER,
tt_midd80pct        INTEGER,
lottr_pmp           REAL,
tt_pmp50pct         INTEGER,
tt_pmp80pct         INTEGER,
lottr_we            REAL,
tt_we50pct          INTEGER,
tt_we80pct          INTEGER,
tttr_amp            REAL,
ttt_amp50pct        INTEGER,
ttt_amp95pct        INTEGER,
tttr_midd           REAL,
ttt_midd50pct       INTEGER,
ttt_midd95pct       INTEGER,
tttr_pmp            REAL,
ttt_pmp50pct        INTEGER,
ttt_pmp95pct        INTEGER,
tttr_we             REAL,
ttt_we50pct         INTEGER,
ttt_we95pct         INTEGER,
tttr_ovn            REAL,
ttt_ovn50pct        INTEGER,
ttt_ovn95pct        INTEGER,
phed                REAL,
metric_source       INTEGER,
comments            TEXT
) WITHOUT ROWID ;


