\set tbl_name 'here_realtime_traffic_':PARTITION_TABLE_SUFFIX
\set full_tbl_name 'here_realtime_traffic_partitions.':tbl_name
\set pkey_idx_name 'here_realtime_traffic_':PARTITION_TABLE_SUFFIX'_pkey'
\set full_pkey_idx_name 'here_realtime_traffic_partitions.here_realtime_traffic_':PARTITION_TABLE_SUFFIX'_pkey'
\set date_constraint :tbl_name'_date_ck'
\set epoch_constraint :tbl_name'_epoch_ck'

BEGIN;

CREATE TABLE IF NOT EXISTS public.here_realtime_traffic (
  tmc             TEXT NOT NULL,

  timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL,

  travel_time     REAL NOT NULL,
  confidence      REAL,
  speed           REAL,
  jam_factor      REAL
) PARTITION BY RANGE (timestamp) ;


-- Epoch includes 0,1,2.5,3,...
--   Window FLOOR(epoch), CEIL(epoch)
CREATE OR REPLACE VIEW public.here_realtime_npmrds
  AS
    SELECT
        tmc,
        timestamp::DATE AS date,
        (
          ( EXTRACT(HOUR FROM timestamp) * 12 )
          +
          FLOOR( EXTRACT(MINUTE FROM timestamp) / 5 )
        )::SMALLINT AS epoch,
        AVG(travel_time) AS travel_time_all_vehicles
      FROM public.here_realtime_traffic
      GROUP BY 1,2,3
;

CREATE SCHEMA IF NOT EXISTS here_realtime_traffic_partitions;

CREATE TABLE :full_tbl_name (
  LIKE public.here_realtime_traffic
) WITH (fillfactor=100, autovacuum_enabled=false) ;

ALTER TABLE :full_tbl_name
  ALTER COLUMN timestamp
    SET DEFAULT :'TIME_RANGE_START'::TIMESTAMP WITHOUT TIME ZONE
;

-- Because we cannot use variables in \COPY, we need a known table name into which to load the CSV.
--   We need to use :TABLE_COLS to make sure the CSV column order is the same as the table col order.
-- SEE: https://www.postgresql.org/docs/current/app-psql.html#APP-PSQL-META-COMMANDS-COPY
CREATE TEMPORARY TABLE tmp_loader_table
  AS 
    SELECT
        :TABLE_COLS
      FROM :full_tbl_name
;

\COPY tmp_loader_table FROM PSTDIN WITH ( FORMAT CSV, HEADER, DELIMITER (',') ) ;

INSERT INTO :full_tbl_name (:TABLE_COLS)
  SELECT
      :TABLE_COLS
    FROM tmp_loader_table
;

DROP TABLE tmp_loader_table;

ALTER TABLE :full_tbl_name
  ADD CONSTRAINT :pkey_idx_name
    PRIMARY KEY (tmc)
;

ALTER INDEX :full_pkey_idx_name
  SET (fillfactor = 100);

ALTER TABLE :full_tbl_name
  ADD CONSTRAINT :date_constraint
    CHECK (
      ( timestamp::DATE >= :'DATE'::DATE )
      AND
      ( timestamp::DATE <  :'NEXT_DATE'::DATE )
    )
;

ALTER TABLE :full_tbl_name
  ADD CONSTRAINT :epoch_constraint
    -- Syntax in CHECK must match syntax generated by VIEW.
    CHECK(
      (
        (
          (DATE_PART('HOUR'::TEXT, "timestamp") * '12'::DOUBLE PRECISION)
          +
          FLOOR((DATE_PART('MINUTE'::TEXT, "timestamp") / '5'::DOUBLE PRECISION))
        )
      )::SMALLINT = :EPOCH
    )
;

ALTER TABLE public.here_realtime_traffic
  ATTACH PARTITION :full_tbl_name
    FOR VALUES FROM (:'TIME_RANGE_START') TO (:'TIME_RANGE_END')
;

CLUSTER :full_tbl_name USING :pkey_idx_name;

COMMIT;
