#!/bin/bash

set -e

if [[ -z "$START_DATE" ]]; then
  ( >&2 echo "ERROR: The START_DATE env variable is required." )
  exit 1
fi

if [[ -z "$END_DATE" ]]; then
  ( >&2 echo "ERROR: The END_DATE env variable is required." )
  exit 1
fi

DATE_RE='[0-9]{8}'

if [[ ! ( "$START_DATE" =~ $DATE_RE && "$END_DATE" =~ $DATE_RE ) ]]; then
  ( >&2 echo "ERROR: The START_DATE & END_DATE must be in YYYYMMDD format" )
  exit 1
fi

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

ETL_DIR="$( realpath '../../etl' )"

mkdir -p "$ETL_DIR"

DOWNLOAD_TIMESTAMP="$( date +'%Y%m%dT%H%M%S' )"
DATE_RANGE="${START_DATE}-${END_DATE}"

WORK_DIR_BASENAME="transcom-events-etl.$DATE_RANGE.$DOWNLOAD_TIMESTAMP"
WORK_DIR_PATH="$ETL_DIR/$WORK_DIR_BASENAME"
if ! mkdir "$WORK_DIR_PATH" 2>/dev/null; then
  echo "ERROR: Cannot create directory $WORK_DIR_PATH. Does it already exist?"
  exit 1
fi

echo "$DOWNLOAD_TIMESTAMP" > "$WORK_DIR_PATH/DOWNLOAD_TIMESTAMP"
echo "$START_DATE" > "$WORK_DIR_PATH/START_DATE"
echo "$END_DATE" > "$WORK_DIR_PATH/END_DATE"

## If this script encounters an error, clean up the WORK_DIR.
function finish {
  echo 'TRAP CALLED'
  rm -rf "$WORK_DIR_PATH"
}
trap finish ERR


### Download the events from TransCom and write in raw form to NDJSON file.
RAW_DOWNLOAD_FILE_NAME="transcom-events.raw-download.$DATE_RANGE.$DOWNLOAD_TIMESTAMP.ndjson.gz"
RAW_DOWNLOAD_FILE_PATH="$WORK_DIR_PATH/$RAW_DOWNLOAD_FILE_NAME"

export START_DATE
export END_DATE

./downloadTranscomData |
  gzip -9 > "$RAW_DOWNLOAD_FILE_PATH"


### Transform the raw NDJSON download to the DB ready CSV
TRANSFORMED_FILE_NAME="transcom-events.$DATE_RANGE.$DOWNLOAD_TIMESTAMP.csv.gz"
TRANSFORMED_FILE_PATH="$WORK_DIR_PATH/$TRANSFORMED_FILE_NAME"

zcat "$RAW_DOWNLOAD_FILE_PATH" |
  ./apiResponseToCSV |
  gzip -9 > "$TRANSFORMED_FILE_PATH"

# Tar the WORK_DIR, cleaning up the original when done.
TRANSCOM_ETL_TAR_ARCHIVE_PATH="$WORK_DIR_PATH.tar"
tar -cf "$TRANSCOM_ETL_TAR_ARCHIVE_PATH" --remove-files -C "$ETL_DIR" "$WORK_DIR_BASENAME"

popd >/dev/null
