#!/usr/bin/env node

const request = require('request-promise-native');

const TRANSCOM_URI =
  'https://eventsearch.xcmdata.org/HistoricalEventSearch/xcmEvent/getEventGridData';

const { START_DATE, END_DATE } = process.env;

if (!(START_DATE && END_DATE)) {
  console.error(
    'ERROR: The START_DATE and END_DATE env variables are required.'
  );
  process.exit(1);
}

const dateRE = /^\d{8}$/;

if (!(START_DATE.match(dateRE) && START_DATE.match(dateRE))) {
  console.error(
    'ERROR: The START_DATE and END_DATE must be in "yyyymmdd" format.'
  );
  process.exit(1);
}

const startDateTime = `${START_DATE.slice(0, 4)}-${START_DATE.slice(
  4,
  6
)}-${START_DATE.slice(6, 8)} 00:00:00`;

const endDateTime = `${END_DATE.slice(0, 4)}-${END_DATE.slice(
  4,
  6
)}-${END_DATE.slice(6, 8)} 23:59:59`;

const options = {
  method: 'POST',
  uri: TRANSCOM_URI,
  body: {
    eventCategoryIds: '1,2,3,4,13',
    eventStatus: '',
    eventType: '',
    state: '',
    county: '',
    city: '',
    reportingOrg: '',
    facility: '',
    primaryLoc: '',
    secondaryLoc: '',
    eventDuration: null,
    // startDateTime: '2019-06-25 12:00:00',
    // endDateTime: '2019-06-25 14:00:00',
    startDateTime,
    endDateTime,
    orgID: '15',
    direction: '',
    iseventbyweekday: 1,
    tripIds: ''
  },
  json: true
};

(async () => {
  try {
    const { data } = await request(options);

    if (!Array.isArray(data)) {
      throw new Error('response data field is not an array');
    }

    data.forEach(e => console.log(JSON.stringify(e)));
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
