#!/bin/bash

set -e

if [[ -z "$START_DATE" ]]; then
  ( >&2 echo "ERROR: The START_DATE env variable is required." )
  exit 1
fi

if [[ -z "$END_DATE" ]]; then
  ( >&2 echo "ERROR: The END_DATE env variable is required." )
  exit 1
fi

DATE_RE='[0-9]{8}'

if [[ ! ( "$START_DATE" =~ $DATE_RE && "$END_DATE" =~ $DATE_RE ) ]]; then
  ( >&2 echo "ERROR: The START_DATE & END_DATE must be in YYYYMMDD format" )
  exit 1
fi

pushd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null

source ./createTranscomEventsETLArchive

echo "Created Transcom Events ETL tar archive:
  $TRANSCOM_ETL_TAR_ARCHIVE_PATH"

echo "Loading events into the database..."
source ./loadData

popd >/dev/null

