#!/usr/bin/env node

/* eslint no-console: 0, camelcase: 0 */

const { execSync } = require('child_process');
const { isAbsolute, join } = require('path');
const envFile = require('node-env-file');
const { Client } = require('pg');

const yargs = require('yargs');

const createTranscomEventsCsvStream = require('./createTranscomEventsCsvStream');
const loadTranscomEvents = require('./loadTranscomEvents');

const cliArgsSpec = {
  transcomEventsNdjsonGzip: {
    demand: true,
    type: 'string',
    describe: 'Path to the GZipped Transcom Events NDJSON file'
  },
  pg_env: {
    demand: true,
    type: 'string',
    default: 'development',
    choices: ['development', 'production']
  }
};

const { argv } = yargs
  .strict()
  .parserConfiguration({
    'camel-case-expansion': false,
    'flatten-duplicate-arrays': false
  })
  .wrap(yargs.terminalWidth() / 1.618)
  .option(cliArgsSpec);

const { transcomEventsNdjsonGzip, pg_env } = argv;

const configFile =
  pg_env === 'production' ? 'postgres.env.prod' : 'postgres.env.dev';

execSync('./create-transcom-historical-events-table', {
  cwd: join(__dirname, '..'),
  env: Object.assign({}, process.env, { PG_ENV: pg_env })
});

const transcomEventsNdjsonGzipPath = isAbsolute(transcomEventsNdjsonGzip)
  ? transcomEventsNdjsonGzip
  : join(process.cwd(), transcomEventsNdjsonGzip);

envFile(join(__dirname, '../../../../config/', configFile));

(async () => {
  const client = new Client();

  try {
    await client.connect();

    const transcomEventsCsvStream = createTranscomEventsCsvStream(
      transcomEventsNdjsonGzipPath
    );

    await loadTranscomEvents(client, transcomEventsCsvStream);

    client.end();
  } catch (err) {
    console.error(err);
  } finally {
    client.end();
  }
})();
