export type TranscomEventID = string;

export enum TransomEventDirection {
  ALL_DIRECTIONS = "all directions",
  BOTH_DIRECTIONS = "both directions",
  EASTBOUND = "eastbound",
  NEGATIVE_DIRECTION = "negative direction",
  NORTHBOUND = "northbound",
  NOT_DIRECTIONAL = "not directional",
  POSITIVE_DIRECTION = "positive direction",
  SOUTHBOUND = "southbound",
  UNKNOWN = "unknown",
  WESTBOUND = "westbound",
}

export enum TranscomEventStatus {
  CLOSED = "closed",
  NEW = "new",
  UPDATED = "updated",
}

export type TranscomEventType =
  | "abandoned"
  | "accident"
  | "accident investigation"
  | "accident road closed"
  | "accident with injuries"
  | "accident with property damage"
  | "airplane crash"
  | "amber alert"
  | "blackout"
  | "brush fire"
  | "building fire"
  | "bus fire"
  | "capacity related"
  | "cargo spill"
  | "collapsed manhole"
  | "collapsed scaffolding"
  | "collapsed sewer grate"
  | "construction"
  | "crash"
  | "crash investigation"
  | "crash road closed"
  | "crash with fatal"
  | "crash with injuries"
  | "crash with property damage"
  | "debris"
  | "debris spill"
  | "delays"
  | "demonstration"
  | "disabled bus"
  | "disabled tractor trailer"
  | "disabled truck"
  | "disabled vehicle"
  | "downed pole"
  | "downed tree"
  | "downed wires"
  | "drawbridge open"
  | "earlier incident"
  | "earthquake damage"
  | "electrical repairs"
  | "emergency construction"
  | "emergency maintenance"
  | "empty and tandem tractor trailer ban"
  | "empty tractor trailer ban"
  | "ems activity"
  | "equipment malfunction"
  | "falling debris"
  | "falling ice"
  | "fire department activity"
  | "flooding"
  | "fluid spill"
  | "fog"
  | "forest fire"
  | "fuel spill"
  | "full commercial vehicle ban"
  | "funeral procession"
  | "gas main break"
  | "grade crossing accident"
  | "gridlock alert day"
  | "hazmat spill"
  | "heavy snow"
  | "heavy traffic"
  | "high winds"
  | "hov rules"
  | "hurricane"
  | "icicle removal"
  | "icing"
  | "jack-knifed tractor trailer"
  | "job action"
  | "landslide"
  | "long term road construction"
  | "malfunctioning traffic light"
  | "minor delays"
  | "misplaced bus"
  | "misplaced commercial vehicle"
  | "misplaced tractor trailer"
  | "missing manhole cover"
  | "missing sewer grate"
  | "motorcycle rally"
  | "nearby building collapse"
  | "new traffic pattern"
  | "no diesel available"
  | "no food available"
  | "no fuel available"
  | "non-vehicle fire/explosion"
  | "no water available"
  | "operational activity"
  | "other"
  | "outside agency assist"
  | "overhead sign repairs"
  | "overheight tractor trailer"
  | "overturned dump truck"
  | "overturned tractor trailer"
  | "overturned truck"
  | "overturned vehicle"
  | "ozone alert"
  | "parking related"
  | "pedestrian"
  | "pedestrian accident"
  | "plowing and salting"
  | "pockets of volume"
  | "police department activity"
  | "pothole repairs"
  | "power failure"
  | "power problems"
  | "report of an incident"
  | "road collapse"
  | "road sweeping"
  | "road treatment in progress"
  | "roadway non-hazmat spill"
  | "roadwork"
  | "rough road"
  | "roving repairs"
  | "rubbernecking"
  | "rubbernecking delays"
  | "security check point"
  | "security related"
  | "separated tractor trailer"
  | "sewer collapse"
  | "sewer main break"
  | "shifted plates"
  | "signal problem"
  | "silver alert"
  | "sinkhole"
  | "slow moving operation"
  | "snow on roadway"
  | "snow removal"
  | "special event"
  | "speed advisory"
  | "speed restriction"
  | "spinout"
  | "split tractor trailer"
  | "steam leak"
  | "stop and go traffic"
  | "storm damage"
  | "street light knockdown"
  | "strorm damage"
  | "stuck gates"
  | "sun glare"
  | "test message"
  | "tornado"
  | "tractor trailer ban"
  | "tractor trailer fire"
  | "traffic congestion"
  | "traffic signal down"
  | "transformer fire"
  | "transit related incident"
  | "truck fire"
  | "truck restrictions"
  | "unanticipated construction delay"
  | "unplanned demonstration"
  | "utility pole down"
  | "utility work"
  | "vehicle fire"
  | "vehicle off the roadway"
  | "vehicle spun out"
  | "vip visit"
  | "watermain break"
  | "weather related"
  | "wet pavement"
  | "wide load";
